@if(collect($censusSeries['rows'])->contains(fn($point)=>collect(['population','male','female','growth','ratio','households','literates'])->contains(fn($key)=>($point[$key]??null)!==null)))
<link rel="stylesheet" href="/css/census-profile.css?v={{ substr(hash_file('sha256',public_path('css/census-profile.css')),0,12) }}">
<section class="panel census-history history-charts"><h2>People through the years</h2>
@php($censusPlots=[['title'=>'Population','unit'=>'people','series'=>[['key'=>'population','label'=>'Population']]],['title'=>'Male and female population','unit'=>'people','series'=>[['key'=>'male','label'=>'Male'],['key'=>'female','label'=>'Female']]],['title'=>'Decadal population growth','unit'=>'%','series'=>[['key'=>'growth','label'=>'Growth']]],['title'=>'Females per 1,000 males','unit'=>'ratio','series'=>[['key'=>'ratio','label'=>'Females per 1,000 males']]],['title'=>'Households','unit'=>'households','series'=>[['key'=>'households','label'=>'Households']]],['title'=>'Literacy','unit'=>'people','series'=>[['key'=>'literates','label'=>'Literate persons']]]])
<div class="history-chart-grid">@foreach($censusPlots as $plot)
@if(collect($censusSeries['rows'])->contains(fn($point)=>collect($plot['series'])->contains(fn($series)=>($point[$series['key']]??null)!==null)))
<section class="history-line" data-history-chart><h3>{{ $plot['title'] }}</h3><script type="application/json" class="history-chart-data">{!! json_encode(['rows'=>$censusSeries['rows'],'series'=>$plot['series'],'unit'=>$plot['unit'],'autoScale'=>true,'singleValueBar'=>true],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
<div class="history-controls"><label>From<select data-chart-from>@foreach($censusSeries['rows'] as $point)<option>{{ $point['year'] }}</option>@endforeach</select></label><label>To<select data-chart-to>@foreach($censusSeries['rows'] as $point)<option @selected($loop->last)>{{ $point['year'] }}</option>@endforeach</select></label></div>
<div class="history-legend" aria-label="Chart series"></div><div class="history-plot"></div><p class="history-readout" role="status">Hover or focus a year to see its value.</p>
<details class="chart-values"><summary><span class="chart-values-closed">Show data table</span><span class="chart-values-open">Hide data table</span><svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="m4 6 4 4 4-4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></summary><div class="table-scroll"><table><thead><tr><th>Year</th>@foreach($plot['series'] as $series)<th>{{ $series['label'] }}</th>@endforeach</tr></thead><tbody>@foreach(array_reverse($censusSeries['rows']) as $point)<tr><th>{{ $point['year'] }}</th>@foreach($plot['series'] as $series)<td>{{ ($point[$series['key']]??null)===null?'—':number_format($point[$series['key']],$plot['unit']==='%'?2:0) }}@if($point['notes']) †@endif</td>@endforeach</tr>@endforeach</tbody></table></div></details></section>
@endif @endforeach</div>
<details class="census-source-notes"><summary>Sources & data notes</summary>@foreach($censusSeries['rows'] as $point)@foreach($point['notes'] as $note)<p class="small">† {{ $point['year'] }}: {{ $note }}</p>@endforeach @endforeach
@if($censusSeries['source'])<p class="small">{{ $censusSeries['source']['boundary_basis'] }} <a href="{{ $censusSeries['source']['url'] }}" target="_blank" rel="noopener">Official population history ↗</a></p>@endif</details></section>@endif
