@extends('seo-layout')
@section('content')
<a href="{{ route('imports.index') }}">Back to data imports</a><h1>Census history & official archives</h1>
<p>Pilibhit / Uttar Pradesh. Catalogue references checked 16 September 2026. This is a growing inventory of verified official sources, not a claim that every historical volume has been found.</p>
@if($hasPopulationHistory)<section class="card"><h2>District history now available</h2><p>1901-2001: 11 Census years, with total, rural and urban population and male/female counts. Extracted from Statement 3 of the official 2001 handbook.</p><a class="button" href="{{ route('census.history') }}">View historical population table & chart</a></section>@endif
@if($has1981)<section class="card"><h2>1981 district and tahsil figures</h2><p>Verified population and household totals, with dropdown navigation to historical village tables. Village profiles remain pending.</p><a href="{{ route('census.1981') }}">Explore 1981 data and village source tables</a></section>@endif
<form class="filters" method="get" action="{{ route('census.archive') }}"><div><label for="census_year">Census edition</label><select id="census_year" name="census_year"><option value="">All verified archive editions</option>@foreach($years as $year)<option value="{{ $year }}" @selected($selectedYear===$year)>{{ $year }}</option>@endforeach</select></div><button>Show editions</button></form>
@foreach($entries as $entry)<article class="card"><h2>{{ $entry['year'] }} / {{ $entry['title'] }}</h2><p>{{ $entry['coverage'] }}</p><p><a href="{{ $entry['url'] }}" target="_blank" rel="noreferrer">Official Census catalogue & downloads</a></p>
@if($entry['village_profiles'])<p>{{ number_format($entry['village_profiles']) }} village profiles currently published for this Census year. This count comes from the imported PCA edition, not necessarily this handbook file.</p><a href="{{ route('villages.index',['year'=>$entry['year']]) }}">Browse village profiles</a>@else<p class="muted">Village profile import for this edition: pending. No current village codes or boundaries have been assigned to these historical records.</p>@endif</article>@endforeach
<p class="notice">A missing edition here means its source has not yet been verified in this inventory, not that historical data does not exist. General district tables, village directories, village surveys and amenities have different coverage and reference dates.</p>
@endsection
