<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
@php
$canonical = route('census.history');
$breadcrumbs = ['India'=>route('home'), 'Pilibhit district'=>route('places.show',['type'=>'district','slug'=>'pilibhit']), 'Historical Census'=>$canonical];
@endphp
@include('seo-metadata', ['seoTitle'=>'Pilibhit historical Census population, 1901-2001 | Pollmedia','seoDescription'=>'Explore official Pilibhit district population from 1901 to 2001, with rural and urban totals, male and female counts, and Census source references.'])
<link rel="stylesheet" href="/css/villages.css"><style>.history-shell{max-width:1100px;margin:auto;padding:30px 22px}.history-card{background:white;border:1px solid #d8e2d9;border-radius:14px;padding:24px;margin:24px 0}.history-filters{display:flex;flex-wrap:wrap;gap:18px;align-items:end}.history-filters label{display:block}.history-filters select,.history-filters button{font:inherit;padding:10px;border-radius:6px}.history-filters button{background:#176c55;color:white;border:0}.history-table{overflow:auto}.history-table table{width:100%;border-collapse:collapse}.history-table th,.history-table td{text-align:left;padding:12px;border-bottom:1px solid #d8e2d9}.history-bar{display:grid;grid-template-columns:55px 1fr 100px;gap:12px;align-items:center;margin:13px 0}.history-track{background:#edf2e9;height:12px}.history-fill{background:#176c55;height:100%}.history-note{color:#52675e;font-size:14px}h1{font-size:clamp(28px,4vw,46px);line-height:1.15}a{color:#176c55}</style></head>
<body><main class="history-shell"><a href="{{ route('places.show',['type'=>'district','slug'=>'pilibhit']) }}">Pollmedia / Pilibhit district</a>
<h1>A century of Census population</h1><p>Pilibhit district / 1901-2001 / official retrospective series</p>
<p>{{ $data['scope'] }}</p>
@if($has1981)<section class="history-card"><h2>Explore the 1981 Census</h2><p>District and tahsil population, households, and direct links to the official village tables.</p><a href="{{ route('census.1981') }}">Browse 1981 Census data</a></section>@endif
<form class="history-filters" method="get" action="{{ route('census.history') }}">
<div><label for="area">Population coverage</label><select id="area" name="area">@foreach(['total'=>'District total','rural'=>'Rural','urban'=>'Urban'] as $key=>$label)<option value="{{ $key }}" @selected($area===$key)>{{ $label }}</option>@endforeach</select></div>
<div><label for="census_year">Census year</label><select id="census_year" name="census_year"><option value="">All available years</option>@foreach($years as $year)<option value="{{ $year }}" @selected($selectedYear===$year)>{{ $year }}</option>@endforeach</select></div><button>Show data</button></form>
<section class="history-card"><h2>{{ ucfirst($area) }} population / historical trend</h2><p class="history-note">All 11 source years; bars start at zero and share the same scale within this chart. Rural/urban classification may change between censuses.</p>
@foreach($series as $row)<div class="history-bar"><span>{{ $row['year'] }}</span><div class="history-track" aria-hidden="true"><div class="history-fill" style="width:{{ 100*$row['population']/$series->max('population') }}%"></div></div><strong>{{ number_format($row['population']) }}</strong></div>@endforeach
</section>
<section class="history-card"><h2>{{ ucfirst($area) }} population table{{ $selectedYear ? ' / '.$selectedYear : '' }}</h2><div class="history-table"><table><caption>{{ $data['source_locator'] }} / Census 2001 handbook</caption><thead><tr><th scope="col">Census year</th><th scope="col">Persons</th><th scope="col">Male</th><th scope="col">Female</th></tr></thead><tbody>@foreach($rows as $row)<tr><th scope="row">{{ $row['year'] }}</th><td>{{ number_format($row['population']) }}</td><td>{{ number_format($row['male']) }}</td><td>{{ number_format($row['female']) }}</td></tr>@endforeach</tbody></table></div>
<p><a href="{{ $data['source_url'] }}#page=20" target="_blank" rel="noreferrer">Official population table (PDF page 20)</a></p>
<p class="history-note">District measurements only. These figures are not village, PC or AC population totals. This historical table ends in 2001; the separately sourced <a href="{{ route('places.show',['type'=>'district','slug'=>'pilibhit']) }}#development">2011 district baseline</a> remains available.</p></section>
<section class="history-card"><h2>Official reference</h2><p><a href="{{ $data['landing'] }}" target="_blank" rel="noreferrer">Census of India 2001, Pilibhit District Census Handbook, Parts A and B</a><br>{{ $data['source_locator'] }} / source checked {{ $data['checked_on'] }}.</p><p class="history-note" style="overflow-wrap:anywhere">Archived file SHA-256: {{ $data['sha256'] }}</p><p>Missing historical indicators have not been filled with zero or estimates. Older village-level tables require separate extraction and identity checks.</p></section>
</main></body></html>
