<!doctype html>
<html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $title }} · Census & civic data · Pollmedia</title>
<link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256', public_path('css/election-dashboard.css')),0,12) }}">
<link rel="stylesheet" href="/css/civic-explorer.css?v={{ substr(hash_file('sha256', public_path('css/civic-explorer.css')),0,12) }}">
<script src="{{ asset('js/instant-filters.js') }}" defer></script>@include('site-theme')</head><body class="election-ui civic-ui">@include('public-header')
@if(request('state'))<p class="notice">No matching state record is available in this edition for {{ request('state') }}. The available state directory is shown below; historical names and boundaries can differ.</p>@endif<div class="dashboard-shell"><main class="dashboard-main">
<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('civic.index',['year'=>$year,'edition'=>$edition?->id,'group'=>$group,'residence'=>$residence]) }}">{{ \App\Services\PublicLanguage::text('India Census') }}</a>@foreach($parents as $parent)<span>/</span><a href="{{ route('civic.place',['record'=>$parent->id,'edition'=>$edition?->id,'group'=>$group,'residence'=>$residence]) }}">{{ $parent->name }}</a>@endforeach @if($place)<span>/</span><span aria-current="page">{{ $place->name }}</span>@endif</nav>
<p class="eyebrow">Census & civic profiles · {{ $year }} source geography</p>@if($place && auth()->user()?->is_admin)<p><a href="{{ route('site.editor',['table'=>'census_catalogue_rows','id'=>$place->id]) }}">Edit Census record</a></p>@endif<h1>{{ $title }}</h1>
<p>{{ $place ? Illuminate\Support\Str::headline(strtolower($place->level)) : 'State → district → tehsil / subdistrict → village or town → ward' }}</p>
<p class="coverage-note">{{ \App\Services\PublicLanguage::text('Explore the data available today. New evidence can be added to these profiles over time. Missing records are not zero. Names and boundaries belong to the selected Census edition.') }}</p>
<nav class="tabs" aria-label="Data group">@foreach(['population'=>'Population','households'=>'Households','literacy'=>'Literacy','work'=>'Work'] as $key=>$label)<a href="{{ request()->fullUrlWithQuery(['group'=>$key,'page'=>null]) }}" @if($group===$key) aria-current="page" @endif>{{ \App\Services\PublicLanguage::text($label) }}</a>@endforeach<a href="#evidence">{{ \App\Services\PublicLanguage::text('Sources & review notes') }}</a></nav>
<section class="panel"><form method="get" class="filters"><input type="hidden" name="group" value="{{ $group }}">@if(!$place)<input type="hidden" name="year" value="{{ $year }}">@endif<div><label for="edition">{{ \App\Services\PublicLanguage::text('Year / available source table') }}</label><select name="edition" id="edition">@foreach($availableEditions as $option)<option value="{{ $option->id }}" @selected($edition?->id===$option->id)>{{ $option->year }} · {{ $option->name }}</option>@endforeach</select></div><div><label for="residence">{{ \App\Services\PublicLanguage::text('Population group') }}</label><select name="residence" id="residence">@foreach($residenceOptions as $option)<option value="{{ $option }}" @selected($residence===$option)>{{ \App\Services\PublicLanguage::text($option) }}</option>@endforeach</select></div><button @disabled(!$edition)>{{ \App\Services\PublicLanguage::text('Show data') }}</button></form></section>
@if($place)
@forelse($records as $row)
@php($values=json_decode($row->values,true))
<div class="metrics">@foreach($measures as $code=>$label)<div class="metric"><span>{{ \App\Services\PublicLanguage::text($label) }} · {{ $residence }}</span><strong>{{ ($values[$code]??null)===null?'Not reported':number_format($values[$code]) }}</strong><span>{{ $year }} · source value</span></div>@endforeach</div>
@foreach(json_decode($row->flags,true) as $flag)<p class="coverage-note">Pending review: {{ $flag }}</p>@endforeach
<p class="small">Extracted record {{ $row->source_row }}. Different source tables remain separate; overlapping records are not added together.</p>
@empty<p class="panel">No matching figures in this source table and population group. Choose another available table or group; the place profile remains available.</p>@endforelse
<section class="panel civic-map"><h2>Locate {{ $place->name }}</h2>
@php($location=collect([$place->name,...$parents->pluck('name')->reverse()->all(),'India'])->implode(', '))
<iframe title="Area locator for {{ $place->name }}" src="https://www.google.com/maps?q={{ rawurlencode($location) }}&amp;output=embed" loading="lazy" referrerpolicy="no-referrer" allowfullscreen></iframe><p class="small">Name-based area locator, not a verified Census or electoral boundary. Historical names may resolve to a present-day location.</p></section>
@endif
<section class="panel" id="areas"><div class="panel-heading"><h2>{{ $place ? 'Explore within '.$place->name : 'Choose a state or union territory' }}</h2><span class="small">{{ $children->total() }} available records</span></div>
@if($childLevels)<form method="get" class="filters"><input type="hidden" name="edition" value="{{ $edition?->id }}"><input type="hidden" name="residence" value="{{ $residence }}"><input type="hidden" name="group" value="{{ $group }}">@if(!$place)<input type="hidden" name="year" value="{{ $year }}">@endif<div><label for="q">Find a place in this selection</label><input id="q" name="q" type="search" value="{{ $input['q']??'' }}" maxlength="100"></div><button>Find place</button></form>@endif
@if($villageBrowse)<p><a class="button" href="{{ route('villages.index',$villageBrowse) }}">Open available village profiles, maps & local associations →</a></p>@endif
<div class="place-list">@forelse($children as $child)<a href="{{ route('civic.place',['record'=>$child->id,'group'=>$group,'residence'=>$residence]) }}"><strong>{{ $child->name }}</strong><span class="small">{{ Illuminate\Support\Str::headline(strtolower($child->level)) }} · {{ $year }} · {{ $child->residence }} →</span></a>@empty<p>No lower-level records match this source selection. Other years and source tables may have different coverage. This does not mean the area has no villages or towns.</p>@endforelse</div>{{ $children->links() }}</section>
<section class="panel" id="evidence"><h2>Sources & available evidence</h2>@if($edition)<p>{{ $edition->scope }}</p><p><a href="{{ $edition->source_url }}" target="_blank" rel="noopener noreferrer">Original Census workbook ↗</a> · <a href="{{ $edition->landing_url }}">Official catalogue & definitions</a></p><p class="small">Retrieved {{ $edition->retrieved_at }}. Published source data may still require administrative review.</p>@endif
<p><a href="{{ route('census-catalogue.index',array_filter(['edition'=>$edition?->id,'state'=>$place?->state_code,'district'=>$place && $place->level!=='STATE'?$place->district_code:null])) }}">Open detailed source records →</a></p>
<p><a href="{{ route('census.source-tables',['year'=>$year]) }}">Browse {{ $year }} original workbook / PDF evidence →</a></p><p class="small">Source-table evidence includes pending-review records. A source covering this state is not automatically a confirmed match to this place.</p>
@if($matchedPlace)<p><a href="{{ route('geography.show',$matchedPlace->slug) }}">All linked indicators, authorities and identifiers for {{ $matchedPlace->name }} →</a></p>@endif</section>
</main><aside class="dashboard-sidebar civic-sidebar" aria-label="Related places and years">
<section class="panel"><p class="eyebrow">Explore another year</p><h2>Census years</h2>@foreach($years as $option)<a class="civic-year" href="{{ route('civic.index',['year'=>$option,'group'=>$group]) }}" @if($year===$option) aria-current="true" @endif>{{ $option }} →</a>@endforeach<p class="small">Changing year starts at its state list. Historical places are not joined by name or reused code alone.</p><a href="{{ route('census.national-history') }}">National history, 1901–2011 →</a></section>
<section class="panel"><p class="eyebrow">Related geography</p><h2>AC, PC & other areas</h2>@forelse($linked as $item)<p><a href="{{ in_array($item['place']->type,['ac','pc','district']) && str_starts_with($item['place']->slug,$item['place']->type.'-') ? route('places.show',['type'=>$item['place']->type,'slug'=>substr($item['place']->slug,strlen($item['place']->type)+1)]) : route('geography.show',$item['place']->slug) }}">{{ $item['place']->name }} · {{ strtoupper($item['place']->type) }}</a><br>@foreach($item['sources'] as $source)<a class="small" href="{{ $source }}">Relationship source {{ $loop->iteration }} ↗</a> @endforeach</p>@empty<p class="small">Verified AC/PC associations are not available for this selection yet. They will appear here when a source-backed link is added.</p>@endforelse</section>
<section class="panel"><h2>More civic data</h2><p>Population, amenities, work, education and authorities belong on the same place profile as evidence becomes available.</p><a href="{{ route('census.source-tables') }}">All published source evidence →</a></section>
</aside></div>@include('public-footer')</body></html>
