<!doctype html>
<html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">@include('seo-metadata',['canonical'=>$place ? route('civic.place',['record'=>$place->id]) : route('civic.index'), 'seoTitle'=>$title.' Census and civic data | Pollmedia', 'seoDescription'=>'Explore published Census data with dated official sources.', 'breadcrumbs'=>['India'=>url('/india'),'Census'=>route('civic.index')]])
<link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256', public_path('css/election-dashboard.css')),0,12) }}">
<link rel="stylesheet" href="/css/civic-explorer.css?v={{ substr(hash_file('sha256', public_path('css/civic-explorer.css')),0,12) }}">
<script src="/js/census-profile.js?v={{ substr(hash_file('sha256',public_path('js/census-profile.js')),0,12) }}" defer></script><script src="{{ asset('js/history-lines.js') }}" defer></script><script src="{{ asset('js/instant-filters.js') }}" defer></script>@include('site-theme')</head><body class="election-ui civic-ui public-place-page">@include('public-header')
@if(request('state'))<p class="notice">No matching state record is available in this edition for {{ request('state') }}. The available state directory is shown below; historical names and boundaries can differ.</p>@endif<div class="dashboard-shell constituency-page"><main class="dashboard-main">
<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('civic.index',['year'=>$year,'edition'=>$edition?->id,'group'=>$group,'residence'=>$residence]) }}">{{ \App\Services\PublicLanguage::text('India Census') }}</a>@foreach($parents as $parent)<span>/</span><a href="{{ route('civic.place',['record'=>$parent->id,'edition'=>$edition?->id,'group'=>$group,'residence'=>$residence]) }}">{{ $parent->name }}</a>@endforeach @if($place)<span>/</span><span aria-current="page">{{ $place->name }}</span>@endif</nav>
<p class="eyebrow">Census · {{ $year }}</p>@if($place && auth()->user()?->is_admin)<p><a href="{{ route('site.editor',['table'=>'census_catalogue_rows','id'=>$place->id]) }}">Edit Census record</a></p>@endif<h1>{{ $title }}</h1>
<p>{{ $place ? Illuminate\Support\Str::headline(strtolower($place->level)) : 'State → district → tehsil / subdistrict → village or town → ward' }}</p>
@if($place && (collect($censusSeries['rows'])->contains(fn($point)=>collect(['population','male','female','households','literates'])->contains(fn($key)=>($point[$key]??null)!==null)) || $records->contains(fn($row)=>collect(json_decode($row->values,true))->contains(fn($value)=>$value!==null && is_numeric($value)))))<p><a class="button" href="#census-years">Year-wise data ↓</a></p>@endif
<nav class="tabs" aria-label="Data group">@foreach(['population'=>'Population','households'=>'Households','literacy'=>'Literacy','work'=>'Work'] as $key=>$label)<a href="{{ request()->fullUrlWithQuery(['group'=>$key,'page'=>null]) }}" @if($group===$key) aria-current="page" @endif>{{ \App\Services\PublicLanguage::text($label) }}</a>@endforeach<a href="#evidence">{{ \App\Services\PublicLanguage::text('Sources') }}</a></nav>
@if(!$place && $stateOptions->isNotEmpty())<section class="panel"><form method="get" action="{{ route('civic.index') }}" class="filters"><input type="hidden" name="group" value="{{ $group }}"><div><label for="year">Census year</label><select name="year" id="year">@foreach($years as $option)<option value="{{ $option }}" @selected($year===$option)>{{ $option }}</option>@endforeach</select></div><button>Choose year →</button></form>
<div class="filters"><div><label for="state-navigation">State</label><select id="state-navigation" onchange="if(this.value) window.location.assign(this.value)"><option value="">Choose a state</option>@foreach($stateOptions as $option)<option value="{{ route('civic.place',['record'=>$option->id,'group'=>$group]) }}" @selected($place?->state_code===$option->state_code)>{{ $option->display_name }}</option>@endforeach</select></div>@if($districtOptions->isNotEmpty())<div><label for="district-navigation">District</label><select id="district-navigation" onchange="if(this.value) window.location.assign(this.value)"><option value="">Choose a district</option>@foreach($districtOptions as $option)<option value="{{ route('civic.place',['record'=>$option->id,'group'=>$group]) }}">{{ $option->name }}</option>@endforeach</select></div>@endif</div></section>@endif


@include('census-profile-charts')
@include('census-selected-year')
@include('census-area-navigation')
@if($children->total()>0 || !empty($input['q']) || $villageBrowse)<section class="panel" id="areas"><div class="panel-heading"><h2>{{ $place ? 'Explore within '.$place->name : 'Choose a state or union territory' }}</h2><span class="small">{{ $children->total() }} available records</span></div>
@if($childLevels)<form method="get" class="filters"><input type="hidden" name="edition" value="{{ $edition?->id }}"><input type="hidden" name="residence" value="{{ $residence }}"><input type="hidden" name="group" value="{{ $group }}">@if(!$place)<input type="hidden" name="year" value="{{ $year }}">@endif<div><label for="q">Search blocks, villages or towns</label><input id="q" name="q" type="search" value="{{ $input['q']??'' }}" maxlength="100"></div><button>Find place</button></form>@endif
@if($villageBrowse)<p><a class="census-text-link" href="{{ route('villages.index',$villageBrowse) }}">Browse village profiles →</a></p>@endif
<div class="place-list">@forelse($children as $child)<a href="{{ route('civic.place',['record'=>$child->id,'group'=>$group,'residence'=>$residence]) }}"><strong>{{ $child->name }}</strong><span class="small">{{ Illuminate\Support\Str::headline(strtolower($child->level)) }} · {{ $year }} · {{ $child->residence }} →</span></a>@empty<p>No lower-level records match this source selection. Other years and source tables may have different coverage. This does not mean the area has no villages or towns.</p>@endforelse</div>{{ $children->links() }}</section>@endif
<details class="panel census-source-notes" id="evidence"><summary>Official sources & data notes</summary><details><summary>Other source records and population groups</summary><section class="panel"><form method="get" class="filters"><input type="hidden" name="group" value="{{ $group }}">@if(!$place)<input type="hidden" name="year" value="{{ $year }}">@endif<div><label for="edition">{{ \App\Services\PublicLanguage::text('Census year and source') }}</label><select name="edition" id="edition">@foreach($availableEditions as $option)<option value="{{ $option->id }}" @selected($edition?->id===$option->id)>{{ $option->year }} · {{ $option->name }}</option>@endforeach</select></div><div><label for="residence">{{ \App\Services\PublicLanguage::text('Population group') }}</label><select name="residence" id="residence">@foreach($residenceOptions as $option)<option value="{{ $option }}" @selected($residence===$option)>{{ \App\Services\PublicLanguage::text($option) }}</option>@endforeach</select></div><button @disabled(!$edition)>{{ \App\Services\PublicLanguage::text('View results') }} →</button></form></section>
</details>@if($edition)<p>{{ $edition->scope }}</p><p><a href="{{ $edition->source_url }}" target="_blank" rel="noopener noreferrer">Original Census workbook ↗</a> · <a href="{{ $edition->landing_url }}">Official catalogue & definitions</a></p>@endif
<p><a href="{{ route('census-catalogue.index',array_filter(['edition'=>$edition?->id,'state'=>$place?->state_code,'district'=>$place && $place->level!=='STATE'?$place->district_code:null])) }}">Open detailed source records →</a></p>
<p><a href="{{ route('census.source-tables',['year'=>$year]) }}">Browse {{ $year }} source workbooks and PDFs →</a></p>
@if($matchedPlace)<p><a href="{{ route('geography.show',$matchedPlace->slug) }}">All linked indicators, authorities and identifiers for {{ $matchedPlace->name }} →</a></p>@endif</details>
</main><aside class="dashboard-sidebar civic-sidebar" aria-label="Map, related places and years">@if($place)@php($location=collect([$place->name,...$parents->pluck('name')->reverse()->all(),'India'])->implode(', '))@include('place-location-map',['mapName'=>$place->name,'mapQuery'=>$location])@endif
@include('census-authorities')
@include('census-related-navigation')
<section class="panel"><p class="eyebrow">Explore another year</p><h2>Census years</h2><nav class="sidebar-links" aria-label="Census years">@foreach($years as $option)<a class="civic-year" href="{{ route('civic.index',['year'=>$option,'group'=>$group]) }}" @if($year===$option) aria-current="page" @endif>{{ $option }} →</a>@endforeach<a href="{{ route('census.national-history') }}">National history, 1901–2011 →</a></nav></section>
@if($linked->isNotEmpty())<section class="panel"><p class="eyebrow">Related places</p><h2>AC, PC & other areas</h2><nav class="sidebar-links" aria-label="Related places">@foreach($linked as $item)<a href="{{ in_array($item['place']->type,['ac','pc','district']) && str_starts_with($item['place']->slug,$item['place']->type.'-') ? route('places.show',['type'=>$item['place']->type,'slug'=>substr($item['place']->slug,strlen($item['place']->type)+1)]) : route('geography.show',$item['place']->slug) }}">{{ $item['place']->name }} · {{ strtoupper($item['place']->type) }} →</a>@endforeach</nav></section>@endif
</aside></div>@include('public-footer')</body></html>



