<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">@include('seo-metadata',['canonical'=>route('constituency.overview',array_filter(['kind'=>$kind,'state'=>$state,'name'=>$latest['entry']->constituency_name,'edition'=>request('edition'),'code'=>request('code')])),'seoTitle'=>\Illuminate\Support\Str::title($name).' · '.($kind==='pc'?'Lok Sabha':'Assembly').' results & history · Pollmedia','seoDescription'=>'Election results, candidate votes, turnout and official source reports for '.$name.'.','breadcrumbs'=>['India'=>url('/india'),$name=>route('constituency.overview',['kind'=>$kind,'state'=>$state,'name'=>$name])]])<link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256',public_path('css/election-dashboard.css')),0,12) }}"><script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script><script src="/js/sortable-tables.js" defer></script>@include('site-theme')<script src="/js/history-lines.js?v={{ substr(hash_file('sha256',public_path('js/history-lines.js')),0,12) }}" defer></script></head><body class="election-ui public-place-page">@include('public-header')
<div class="dashboard-shell constituency-page"><main class="dashboard-main">
@php $winner=$latest['result']['winner']??null; $winningParty=$latest['result']['party']??null; @endphp
@php
$statePage=app(\App\Services\ElectionGeographySummary::class)->states()->first(fn($item)=>mb_strtolower($item['name'])===mb_strtolower($state));
$placeTrail=[['label'=>'India','url'=>route('home')],['label'=>$state,'url'=>$statePage?route('states.show',['state'=>$statePage['slug'],'election'=>$kind]):null],['label'=>\Illuminate\Support\Str::title($name),'url'=>null]];
@endphp
@include('place-heading',['headingName'=>\Illuminate\Support\Str::title($name),'headingType'=>$kind==='pc'?'Lok Sabha constituency':'Assembly constituency (AC)','placeTrail'=>$placeTrail])
<nav class="seat-tabs seat-page-actions" aria-label="On this page"><a href="#representative">Representative</a><a href="#history">Election history</a><a href="#year-detail">Results by year</a><a href="{{ route('constituency.overview',array_filter(['kind'=>$kind,'state'=>$state,'name'=>$name,'format'=>'report','edition'=>$exactSeatOnly?$chosen['entry']->edition_id:null,'code'=>$exactSeatOnly?$chosen['entry']->record_code:null])) }}" target="_blank" rel="noopener">Historical report / PDF ↗</a></nav>
@include('constituency-dashboard-switcher')
@include('election-map',['mapKind'=>$kind,'mapStateName'=>$state,'mapSelectedName'=>$name,'mapMode'=>'focus'])
@include('constituency-district-dashboard-context')
@include('place-history-charts')
@php $hasSourceReportedPolled=false; @endphp
@if($modernSeatScope ?? false)<p class="notice">This dashboard covers {{ $name }} AC {{ $rows->first()['entry']->record_code }} from 2012 onwards. Older same-name records contain distinct same-name seats and are not merged into this history. Their original source records remain available in the <a href="{{ route('elections.constituencies',['kind'=>$kind,'state'=>$state,'q'=>$name]) }}">election directory</a>. Boundary equivalence across editions is unverified.</p>@endif
<section id="history" class="panel"><div class="panel-heading"><div><p class="kicker">The long view</p><h2>Election history</h2></div><span>{{ $rows->pluck('entry.year')->unique()->count() }} available years</span></div>@if($exactSeatOnly)<p class="notice">Several seats share this name. This page shows the selected seat.</p>@endif<div class="table-scroll"><table data-sortable><thead><tr><th data-sort-type="number">{{ \App\Services\PublicLanguage::text('Year') }}</th><th>{{ \App\Services\PublicLanguage::text('Winner') }}</th><th>{{ \App\Services\PublicLanguage::text('Party') }}</th><th data-sort-type="number">Votes polled</th><th data-sort-type="number">Turnout %</th><th data-sort-type="number">{{ \App\Services\PublicLanguage::text('Margin') }}</th><th>Result</th></tr></thead><tbody>
@foreach(($historyRows??$rows) as $row)@php $record=$row['record']; $result=$row['result']; $summary=$record?app(\App\Services\HistoricalElectionAnalytics::class)->summarize([$record]):[]; $sourceReportedPolled=($summary['polled']??null)===null && is_int($record['votes_polled']??null) && $record['votes_polled']>0 ? $record['votes_polled'] : null; $hasSourceReportedPolled=$hasSourceReportedPolled || $sourceReportedPolled!==null; $resultPath=route('constituency.overview',['kind'=>$kind,'state'=>$state,'name'=>$name,'edition'=>$row['entry']->edition_id,'code'=>$row['entry']->record_code],false); @endphp
<tr><th>{{ $row['entry']->year }}</th><td>@if($result){{ $result['winner'] }}@if($record['has_warning']) †@endif @elseif($row['source_candidate'])Reported candidate*: {{ $row['source_candidate']['name'] }}@elseif($record) See source table*@else —@endif</td><td>{{ $result['party']??$row['source_candidate']['party']??'—' }}</td><td>{{ isset($summary['polled'])?number_format($summary['polled']).(($summary['turnout_review_count']??0)?' †':''):($sourceReportedPolled===null?'—':number_format($sourceReportedPolled).' ‡') }}</td><td>{{ isset($summary['turnout'])?number_format($summary['turnout'],2).(($summary['turnout_review_count']??0)?' †':''):'—' }}</td><td>{{ ($result['uncontested']??false)?'Uncontested':(isset($result['margin'])?number_format($result['margin']).($record['has_warning']?' †':''):'—') }}</td><td><a href="{{ $resultPath }}#year-detail">{{ $row['entry']->year }} →</a>@if(!$result && $row['source']) · <a href="{{ $row['source'] }}">Official source ↗</a>@endif · <a href="{{ route('feedback.create',['path'=>$resultPath,'category'=>'data']) }}">Report issue</a></td></tr>@endforeach
</tbody></table>@if(isset($historyRows) && $historyRows->count()<$rows->count())<p class="small">Identical 2019 results in the reports including and excluding Vellore are shown once. Both original report editions remain linked below.</p>@endif</div>@if($hasSourceReportedPolled)<p class="small">‡ Vote count from the linked source record; it is not used for a comparable turnout percentage. Open that year for its data note and official report.</p>@endif @if($rows->contains(fn (array $row): bool => $row['record'] && ! $row['result']))<p class="small">* A candidate or source table is recorded, but a winner has not been confirmed here. Check the linked official report.</p>@endif</section>
<details class="panel"><summary>Original report editions & verification</summary><ul>@foreach($rows as $row)<li><a href="{{ route('constituency.overview',['kind'=>$kind,'state'=>$state,'name'=>$name,'edition'=>$row['entry']->edition_id,'code'=>$row['entry']->record_code]) }}#year-detail">{{ $row['entry']->edition_label }}</a>@if($row['source']) · <a href="{{ $row['source'] }}">Official source ↗</a>@endif</li>@endforeach</ul></details>
<section id="year-detail" class="panel"><h2>{{ \App\Services\PublicLanguage::text('Election results') }}</h2><form method="get" class="filters"><input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="state" value="{{ $state }}"><input type="hidden" name="name" value="{{ $name }}">@if($exactSeatOnly)<input type="hidden" name="code" value="{{ $chosen['entry']->record_code }}">@endif<label for="edition">Election year</label><select name="edition" id="edition">@foreach($rows->groupBy('entry.year')->map(fn($group)=>$group->first(fn($item)=>$item['entry']->edition_id===($chosen['entry']->edition_id??null))??$group->first(fn($item)=>$item['record']!==null)??$group->first()) as $row)<option value="{{ $row['entry']->edition_id }}" @selected(($chosen['entry']->edition_id??null)===$row['entry']->edition_id)>{{ $row['entry']->year }}</option>@endforeach</select><button>Show results</button></form>
@if($chosen && $chosen['record'])@php $selected=$chosen['record']; @endphp
<h3>{{ $chosen['entry']->year }} results</h3>@if($chosen['result']['uncontested']??false)<p>Uncontested: {{ $chosen['result']['winner'] }} was returned without a poll. Votes and winning margin are not reported.</p>@elseif(!$chosen['result'])<p class="notice">* @if(!empty($selected['candidates']))Candidate rows below are shown as recorded;@else Candidate rows could not be extracted reliably;@endif a winner has not been confirmed here. <a href="{{ $chosen['source'] }}">Check the official report ↗</a></p>@endif @include('constituency-election-analysis')
@if($selected['has_warning'])<p class="notice">† {{ $selected['error']??'This report needs review. Figures below retain the source values.' }} @if(($selected['source_discrepancy']['field']??'')==='reported_total')Workbook total: {{ number_format($selected['source_discrepancy']['workbook_value']) }}; candidate rows and official summary: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @elseif(($selected['source_discrepancy']['field']??'')==='candidate_total')Candidate rows: {{ number_format($selected['source_discrepancy']['candidate_sum']) }}; official summary: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @elseif(($selected['source_discrepancy']['field']??'')==='elector_components')Source elector components: {{ number_format($selected['source_discrepancy']['component_value']) }}; official summary total: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @endif @if(isset($selected['summary_totals']['valid_candidate_votes'],$selected['valid_candidate_votes']) && $selected['summary_totals']['valid_candidate_votes']!==$selected['valid_candidate_votes'] && ($selected['source_warning_code']??'')!=='workbook_pdf_summary')Detailed candidate votes: {{ number_format($selected['valid_candidate_votes']) }}; report summary: {{ number_format($selected['summary_totals']['valid_candidate_votes']) }}. @endif<a href="{{ $chosen['source'] }}">Check the official report ↗</a></p>@endif
<div class="table-scroll"><table data-sortable><thead><tr><th>{{ \App\Services\PublicLanguage::text('Candidate') }}</th><th>Party at election</th><th data-sort-type="number">{{ \App\Services\PublicLanguage::text('Votes') }}</th></tr></thead><tbody>@foreach($selected['candidates'] as $candidate)<tr><td>{{ $candidate['candidate_name'] }}</td><td>{{ $candidate['party_at_election']??'—' }}</td><td>{{ ($chosen['result']['uncontested']??false) && ($candidate['votes']??null)===0 ? '—' : (isset($candidate['votes'])?number_format($candidate['votes']):'—') }}</td></tr>@endforeach</tbody></table></div><p><a href="{{ $chosen['source'] }}">Official source ↗</a> · <a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$chosen['entry']->edition_id,'state'=>$chosen['entry']->state_label,'code'=>$chosen['entry']->record_code,'format'=>'report']) }}">Print report</a> · <a href="{{ route('feedback.create',['path'=>route('constituency.overview',['kind'=>$kind,'state'=>$state,'name'=>$name,'edition'=>$chosen['entry']->edition_id,'code'=>$chosen['entry']->record_code],false),'category'=>'data']) }}">Report a problem with this result</a></p>
@elseif($chosen)<p>This election report is temporarily unavailable.</p>@else<p>Choose a year for candidate votes, party shares and the detailed result.</p>@endif</section>
@include('election-methodology',['isStateHistory'=>false])
</main><aside class="dashboard-sidebar" aria-label="Related places">
<section id="representative" class="panel representative-card"><div class="representative-avatar" aria-hidden="true">{{ $kind==='pc'?'MP':'MLA' }}</div><div><p class="kicker">Latest available election · {{ $latest['entry']->year }}</p><h2>{{ $winner ?: 'Winner unavailable' }}@if($winner && $latest['record']['has_warning']) †@endif</h2>@if($winner)<p>{{ $winningParty??'' }} · Winner in {{ $latest['entry']->year }}</p>@endif @if($winner && $latest['record']['has_warning'])<p class="small"><a href="#year-detail">† See the result’s data note</a></p>@endif<p class="small">Election winners may differ from current representatives.</p>@if($latest['source'])<a href="{{ $latest['source'] }}" rel="noopener">Official election source ↗</a>@endif</div></section>
@if($related->isNotEmpty())<section class="panel"><h2>Connected places</h2><nav aria-label="Connected constituencies and districts">@foreach($related as $place)<a href="{{ $place->url ?? route('places.show',['type'=>$place->type,'slug'=>substr($place->slug,strlen($place->type)+1)]) }}"><span class="kicker">{{ ['pc'=>'Lok Sabha','ac'=>'Assembly · AC','district'=>'District'][$place->type] }}</span><strong>{{ $place->name }} →</strong>@if($place->reference??false)<small>Official district reference</small>@endif</a>@endforeach</nav></section>@endif<div class="panel"><h2>Explore further</h2><nav aria-label="Related places"><a href="#history">Compare election years</a><a href="{{ route('elections.constituencies',['state'=>$state,'kind'=>$kind]) }}">More places in {{ $state }}</a><a href="{{ route('elections.history') }}">Lok Sabha results</a><a href="{{ route('elections.assembly') }}">Assembly results</a><a href="{{ route('elections.by-election-results') }}">By-election results</a></nav></div></aside></div>@include('public-footer')</body></html>
