<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ \Illuminate\Support\Str::title($name) }} · {{ $kind==='pc'?'Lok Sabha':'Assembly' }} results & history · Pollmedia</title><link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256',public_path('css/election-dashboard.css')),0,12) }}"><script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script><script src="/js/sortable-tables.js" defer></script></head><body class="election-ui">@include('public-header')
<div class="dashboard-shell constituency-page"><main class="dashboard-main">
@php $safeLatest=$latest['record'] && !$latest['record']['has_warning'] && ($latest['record']['number_of_seats']??1)===1; $winner=$safeLatest?($latest['record']['winner']??null):null; $winningCandidate=collect($latest['record']['candidates']??[])->firstWhere('candidate_name',$winner); @endphp
<section class="seat-hero"><p class="kicker">{{ $state }} / {{ $kind==='pc'?'Lok Sabha · PC':'State Assembly · AC' }}</p><h1>{{ \Illuminate\Support\Str::title($name) }}</h1><p>People, votes and the story across elections.</p><nav class="seat-tabs" aria-label="On this page"><a href="#representative">Representative</a><a href="#history">Election history</a><a href="#year-detail">Results by year</a></nav></section>
@include('place-history-charts')
<section id="history" class="panel"><div class="panel-heading"><div><p class="kicker">The long view</p><h2>Election history</h2></div><span>{{ $rows->pluck('entry.year')->unique()->count() }} available years</span></div><p class="small">Compare reports carrying this name and state. Boundaries and seat definitions may change between elections; matching names alone do not confirm unchanged boundaries.</p><div class="table-scroll"><table data-sortable><thead><tr><th data-sort-type="number">Year</th><th>Winner</th><th>Party</th><th data-sort-type="number">Votes polled</th><th data-sort-type="number">Turnout %</th><th data-sort-type="number">Margin</th><th>Result</th></tr></thead><tbody>
@foreach($rows as $row)@php $record=$row['record']; $safe=$record && !$record['has_warning'] && ($record['number_of_seats']??1)===1; $candidate=$safe?collect($record['candidates'])->firstWhere('candidate_name',$record['winner']??null):null; $summary=$record?app(\App\Services\HistoricalElectionAnalytics::class)->summarize([$record]):[]; @endphp
<tr><th>{{ $row['entry']->year }}</th><td>{{ $safe?($record['winner']??'—'):'Under review' }}</td><td>{{ $candidate['party_at_election']??'—' }}</td><td>{{ isset($summary['polled'])?number_format($summary['polled']):'—' }}</td><td>{{ isset($summary['turnout'])?number_format($summary['turnout'],2):'—' }}</td><td>{{ $safe && isset($record['margin'])?number_format($record['margin']):'—' }}</td><td><a href="{{ route('constituency.overview',['kind'=>$kind,'state'=>$state,'name'=>$name,'edition'=>$row['entry']->edition_id]) }}#year-detail">{{ $row['entry']->edition_label }} →</a></td></tr>@endforeach
</tbody></table></div></section>
<section id="year-detail" class="panel"><h2>Election results</h2><form method="get" class="filters"><input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="state" value="{{ $state }}"><input type="hidden" name="name" value="{{ $name }}"><label for="edition">Election year</label><select name="edition" id="edition">@foreach($rows as $row)<option value="{{ $row['entry']->edition_id }}" @selected(($chosen['entry']->edition_id??null)===$row['entry']->edition_id)>{{ $row['entry']->edition_label }}</option>@endforeach</select><button>Show results</button></form>
@if($chosen && $chosen['record'])@php $selected=$chosen['record']; @endphp
<h3>{{ $chosen['entry']->edition_label }} results</h3>@include('constituency-election-analysis')
@if($selected['has_warning'])<p class="notice">{{ $selected['error']??'This report needs review. Figures below retain the source values.' }}</p>@endif
<div class="table-scroll"><table data-sortable><thead><tr><th>Candidate</th><th>Party at election</th><th data-sort-type="number">Votes</th></tr></thead><tbody>@foreach($selected['candidates'] as $candidate)<tr><td>{{ $candidate['candidate_name'] }}</td><td>{{ $candidate['party_at_election']??'—' }}</td><td>{{ isset($candidate['votes'])?number_format($candidate['votes']):'—' }}</td></tr>@endforeach</tbody></table></div><p><a href="{{ $chosen['source'] }}">Official source ↗</a> · <a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$chosen['entry']->edition_id,'state'=>$state,'code'=>$chosen['entry']->record_code,'format'=>'report']) }}">Print report</a></p>
@elseif($chosen)<p>This election report is temporarily unavailable.</p>@else<p>Choose a year for candidate votes, party shares and the detailed result.</p>@endif</section>
</main><aside class="dashboard-sidebar">@include('place-location-card', ['locationName'=>\Illuminate\Support\Str::title($name),'locationRegion'=>$state,'locationType'=>$kind==='pc'?'Parliamentary constituency':'Assembly constituency'])
<section id="representative" class="panel representative-card"><div class="representative-avatar" aria-hidden="true">{{ $kind==='pc'?'MP':'MLA' }}</div><div><p class="kicker">Representation / latest available election · {{ $latest['entry']->year }}</p><h2>{{ $winner ?: 'Representative information awaiting verification' }}</h2>@if($winner)<p>{{ $winningCandidate['party_at_election']??'' }} · Elected in {{ $latest['entry']->year }}</p>@endif<p class="small">Current office-holder status has not yet been verified. The election winner shown here may differ following a by-election or change of office.</p>@if($latest['source'])<a href="{{ $latest['source'] }}" rel="noopener">Official election source ↗</a>@endif</div></section>
@if($related->isNotEmpty())<section class="panel"><h2>Connected places</h2><nav aria-label="Connected constituencies and districts">@foreach($related as $place)<a href="{{ $place->url ?? route('places.show',['type'=>$place->type,'slug'=>substr($place->slug,strlen($place->type)+1)]) }}"><span class="kicker">{{ ['pc'=>'Lok Sabha · PC','ac'=>'Assembly · AC','district'=>'District'][$place->type] }}</span><strong>{{ $place->name }} →</strong>@if($place->reference??false)<small>Official district reference</small>@endif</a>@endforeach</nav></section>@endif<div class="panel"><h2>Explore further</h2><nav aria-label="Related places"><a href="#history">Compare election years</a><a href="{{ route('elections.constituencies',['state'=>$state,'kind'=>$kind]) }}">More places in {{ $state }}</a><a href="{{ route('elections.history') }}">Lok Sabha results</a><a href="{{ route('elections.assembly') }}">Assembly results</a><a href="{{ route('elections.by-election-results') }}">By-election results</a></nav></div></aside></div></body></html>