<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>{{ $scopeLabel }} · {{ $period }} report draft</title>
<style>body{font:16px/1.6 system-ui,sans-serif;color:#173d37;background:#f5f6f0;margin:0}main{max-width:1000px;margin:auto;padding:32px}a{color:#176c55}.card{background:white;border:1px solid #d5dfd5;border-radius:10px;padding:24px;margin:20px 0}.notice{border-left:4px solid #b89b59;padding:18px;background:#fff8e8}.toolbar{display:flex;gap:14px;flex-wrap:wrap;align-items:center}button,select{font:inherit;padding:8px}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #ddd}.reference{overflow-wrap:anywhere}h1{line-height:1.2}@media print{.toolbar{display:none}body{background:white}main{padding:0}.card{break-inside:avoid}thead{display:table-header-group}}@media(max-width:600px){main{padding:16px}.card{padding:14px}}@page{size:A4;margin:16mm}</style></head><body><main>
@if(!($standalone ?? false))
<nav class="toolbar"><a href="{{ route('home') }}">Pollmedia</a><a href="{{ route('reports.archive') }}">Saved drafts</a>
<form method="get"><label for="edition">Edition</label><select name="edition" id="edition"><option value="quarterly" @selected($edition === 'quarterly')>Quarterly</option><option value="annual" @selected($edition === 'annual')>Annual</option></select><button>Generate</button></form>
<button onclick="window.print()">Print / save PDF</button><a href="{{ route('reports.coverage', ['scope' => $scope, 'edition' => $edition, 'download' => 1]) }}">Download HTML</a>
@if(auth()->user()?->is_admin)<form method="post" action="{{ route('reports.store') }}">@csrf<input type="hidden" name="scope" value="{{ $scope }}"><input type="hidden" name="edition" value="{{ $edition }}"><button>Save dated draft</button></form>@endif</nav>
@endif
<h1>{{ $scopeLabel }}<br>{{ $period }} · {{ ucfirst($edition) }} coverage report</h1><p>Generated {{ $generatedAt->format('d M Y, H:i') }} IST</p>
<p class="notice">Draft for review. This describes the records available in Pollmedia, not complete {{ $scopeLabel }} statistics or changes during this reporting period. Districts, parliamentary constituencies and assembly constituencies overlap and are not added into population or vote totals.</p>
<section class="card"><h2>Geographic profiles in scope</h2><table><thead><tr><th>Geography</th><th>Recorded profiles</th></tr></thead><tbody>
@foreach($coverage as $row)<tr><td>{{ ['pc' => 'Parliamentary constituency', 'ac' => 'Assembly constituency', 'district' => 'District'][$row->type] ?? ucfirst($row->type) }}</td><td>{{ number_format($row->total) }}</td></tr>@endforeach
</tbody></table><p>Uttar Pradesh scope uses accepted geographic identifiers. India scope includes recorded places identified as Indian. These counts do not establish complete boundary coverage.</p></section>
<section class="card"><h2>Published election coverage</h2><table><thead><tr><th>Election year</th><th>Election type</th><th>Constituencies with accepted results</th></tr></thead><tbody>
@forelse($elections as $row)<tr><td>{{ $row->year }}</td><td>{{ ucfirst(str_replace('_', ' ', $row->election_type)) }}</td><td>{{ number_format($row->constituencies) }}</td></tr>@empty<tr><td colspan="3">No published election results in this scope.</td></tr>@endforelse
</tbody></table><p>Each constituency is counted once within its year and election type. Unpublished archive extractions are excluded. Results retain their original election year.</p></section>
<section class="card"><h2>Data gaps and interpretation</h2><p>State and national population totals, development trends, turnout and party vote totals are not calculated from this partial coverage. Historical boundary changes require edition-specific comparisons. Water, health, education and employment indicators will appear as validated datasets become available.</p></section>
<section class="card"><h2>Sources & references</h2>
@forelse($references as $reference)<div class="reference"><h3>{{ $loop->iteration }}. {{ $reference->publisher }}</h3><a href="{{ $reference->url }}">Official source</a><p>Release {{ $reference->id }} · Retrieved {{ $reference->retrieved_at }} UTC</p><p>SHA-256: {{ $reference->sha256 ?? 'Not recorded' }}</p></div>@empty<p>No source editions attached to the available records.</p>@endforelse
</section></main></body></html>
