<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $data['name'] }} district | Pollmedia</title><link rel="stylesheet" href="{{ asset('css/pilibhit-ac-pilot.css') }}"><link rel="stylesheet" href="{{ asset('css/rampur-district-pilot.css') }}"><script src="{{ asset('js/history-lines.js') }}" defer></script><script src="{{ asset('js/district-dashboard-controls.js') }}" defer></script></head>
<body class="rampur-dashboard"><header><a class="brand" href="https://pollmedia.org">Pollmedia<span>District dashboard</span></a><a href="{{ route('district-dashboard-directory') }}">All districts</a></header><main>
@php
$total=$data['totals']['Total'];
$display=fn($value,$digits=0)=>$value===null?'Unavailable':number_format($value,$digits);
$share=fn($value,$denominator)=>$value!==null&&$denominator>0?100*$value/$denominator:null;
@endphp
@if(($data['census_district_code'] ?? '')==='176')<p class="notice">Census 2011 and SOI source records use Bara Banki; the dated election fixture uses Barabanki. This name correspondence does not verify matching boundary editions. <a href="https://censusindia.gov.in/nada/index.php/catalog/6367">Census district 09/176</a> | <a href="https://barabanki.nic.in/about-district/geography/">Official district geography</a>.</p>@endif
<section class="district-title"><div><p class="eyebrow">Census {{ $data['year'] }} · published records</p><h1>{{ $data['name'] }} district</h1></div><label>Change district<select id="district-picker"><option value="{{ request()->url() }}" selected>{{ $data['name'] }}</option><option value="{{ route('rampur-district-pilot') }}">Rampur</option><option value="{{ route('pilibhit-district-pilot') }}">Pilibhit</option><option value="{{ route('district-dashboard-directory') }}">All districts</option></select></label></section>
@if($sourceMap) @include('district-source-map') @else <p class="notice">A source village map has not yet been prepared for this district.</p> @endif
<nav class="section-nav" aria-label="Dashboard sections"><a href="#overview">District overview</a><a href="#subdistricts">Subdistricts</a><a href="#towns">Towns</a>@if($sourceMap)<a href="#map">Village map</a>@endif<a href="#villages">Village directory</a><a href="#history">History & graphs</a><a href="#elections">AC / PC elections</a><a href="{{ route('district-dashboard-directory') }}">All districts</a><a href="#sources">Sources & coverage</a></nav>
<section id="overview" class="metrics">@foreach(['population'=>'Population','households'=>'Households','literacy'=>'Literacy age 7+'] as $key=>$label)<article><span>{{ $label }}</span><strong>{{ $display($total[$key],$key==='literacy'?2:0) }}{{ $key==='literacy'&&$total[$key]!==null?'%':'' }}</strong><small>Census {{ $data['year'] }}</small></article>@endforeach<article><span>Female per 1,000 male</span><strong>{{ $display($total['female']!==null&&$total['male']>0?1000*$total['female']/$total['male']:null) }}</strong><small>Census {{ $data['year'] }} sex ratio</small></article></section>
<section class="panel"><p class="eyebrow">What the figures mean</p><h2>{{ $data['name'] }} at a glance</h2><div class="source-grid"><article><h3>{{ $display($share($data['totals']['Rural']['population']??null,$total['population']),1) }}% rural</h3><p>Residents who lived in rural areas in {{ $data['year'] }}.</p></article><article><h3>{{ $display($total['male_literacy'],1) }}% / {{ $display($total['female_literacy'],1) }}%</h3><p>Male / female literacy among people aged 7+.</p></article><article><h3>{{ $display($share($total['children'],$total['population']),1) }}% aged 0–6</h3><p>{{ $display($total['children']) }} young children recorded.</p></article><article><h3>{{ $display($share($total['workers'],$total['population']),1) }}% workers</h3><p>Main and marginal workers as a share of all residents. This is Census worker participation, not an unemployment rate.</p></article></div><p class="muted">These describe {{ $data['year'] }} conditions; the figures do not estimate today’s population. Missing values remain unavailable.</p></section>
@if(($total['population']??0)>0 && isset($data['totals']['Urban']['population'],$data['totals']['Rural']['population'],$total['literacy'],$total['male_literacy'],$total['female_literacy'])) @include('rampur-district-charts') @endif
<section class="panel"><h2>Rural & urban</h2><div class="source-grid">@foreach(['Rural','Urban'] as $kind) @php($area=$data['totals'][$kind]??[])<article><p class="eyebrow">{{ $kind }}</p><h3>{{ $display($area['population']??null) }} people</h3>@if(isset($area['population'])&&$total['population']>0)<progress aria-label="{{ $kind }} share of district population" max="{{ $total['population'] }}" value="{{ $area['population'] }}" style="width:100%;accent-color:#176953"></progress>@endif<p>{{ $display($share($area['population']??null,$total['population']),1) }}% of district · {{ $display($area['households']??null) }} households</p><p>Literacy 7+: {{ $display($area['literacy']??null,2) }}%</p></article>@endforeach</div></section>
@foreach(['subdistricts'=>'Subdistricts','towns'=>'Towns'] as $key=>$label)<section id="{{ $key }}" class="panel"><p class="eyebrow">Published Census {{ $data['year'] }} units</p><h2>Compare {{ count($data[$key]) }} {{ strtolower($label) }}</h2><div class="table-wrap"><table><thead><tr><th>Place / Census code</th><th>Population</th><th>District share</th><th>Households</th><th>Literacy 7+</th></tr></thead><tbody>@forelse($data[$key] as $place)<tr><td><a href="{{ route('civic.place',['record'=>$place['id']]) }}">{{ $place['name'] }}</a><small>{{ $place['code'] }}</small></td><td>{{ $display($place['population']) }}</td><td>@if($place['population']!==null&&$total['population']>0)<progress aria-label="{{ $place['name'] }} population share" max="{{ $total['population'] }}" value="{{ $place['population'] }}"></progress> {{ $display($share($place['population'],$total['population']),1) }}%@else Unavailable @endif</td><td>{{ $display($place['households']) }}</td><td>{{ $display($place['literacy'],2) }}{{ $place['literacy']!==null?'%':'' }}</td></tr>@empty<tr><td colspan="5">No published {{ strtolower($label) }} records available.</td></tr>@endforelse</tbody></table></div></section>@endforeach
<section id="villages" class="panel"><p class="eyebrow">Published Census records</p><h2>Village directory · {{ $data['year'] }}</h2><p class="notice">{{ $data['census_village_rows'] }} published village records are available. These are Census records, not an accepted LGD directory. Map-to-Census and LGD links remain pending; map selection does not assign population.</p><label>Find a Census village<input id="village-search" type="search" maxlength="120" placeholder="Village name or Census code"></label><p id="village-results" role="status"></p><div class="table-wrap"><table id="census-villages"><thead><tr><th>Village / Census code</th><th>Population</th><th>Households</th><th>Literacy 7+</th></tr></thead><tbody>@forelse(($data['census_villages']??[]) as $place)<tr><td><a href="{{ route('civic.place',['record'=>$place['id']]) }}">{{ $place['name'] }}</a><small>{{ $place['code'] }}</small></td><td>{{ $display($place['population']) }}</td><td>{{ $display($place['households']) }}</td><td>{{ $display($place['literacy'],2) }}{{ $place['literacy']!==null?'%':'' }}</td></tr>@empty<tr data-empty><td colspan="4">Village Census records are unavailable in the selected published sources.</td></tr>@endforelse</tbody></table></div></section>
@include('district-dashboard-history') @include('district-dashboard-elections')
<section id="sources" class="panel"><h2>Sources & coverage</h2><p>Published database records are read on every request. Newly published imports appear when this page reloads.</p><p>{{ $data['census_village_rows'] }} village Census rows are available in the selected published sources. Missing records remain unavailable.</p>@foreach($data['census_editions'] as $edition)<p><a href="{{ $edition['source_url'] }}">{{ $edition['source_key'] }} · official source</a></p>@endforeach</section>
</main><footer>Pollmedia · {{ $data['name'] }} district · Census {{ $data['year'] }} and dated sources</footer></body></html>

