<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Pilibhit district · {{ $period }} report draft · Pollmedia</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f6f0;color:#173d37;font:16px/1.65 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:36px 24px}h1{font-size:42px;line-height:1.15}h2{font-size:26px}a{color:#176c55;text-underline-offset:3px}.toolbar{display:flex;gap:16px;flex-wrap:wrap;align-items:center;padding:20px;background:#e4ede1}button,select,.button{font:inherit;padding:10px 14px;border:1px solid #b8cabd;border-radius:6px;background:white;color:#173d37}.button{text-decoration:none}.kicker,small,.small{font-size:12px;color:#65766c}.notice{background:#fff8e8;border-left:3px solid #b89b59;padding:18px}.card{background:white;border:1px solid #dce5dc;border-radius:10px;padding:22px;margin:20px 0}.stats{display:flex;gap:24px;flex-wrap:wrap}.stats strong{display:block;font-size:30px}.table{overflow:auto}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #dce5dc;padding:10px}th{background:#eef3eb}.hash{overflow-wrap:anywhere}section{margin:30px 0}footer{border-top:1px solid #dce5dc;padding-top:20px}@media(max-width:600px){h1{font-size:32px}main{padding:20px 16px}td,th{padding:8px;font-size:13px}}@media print{body{background:white;color:#111;font-size:11pt}main{max-width:none;padding:0}.toolbar{display:none}.card{break-inside:avoid;border-color:#ccc}thead{display:table-header-group}tr{break-inside:avoid}a{color:#111}.table{overflow:visible}h1{font-size:26pt}h2{break-after:avoid}section{margin:20px 0}@page{size:A4;margin:16mm}}</style><script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script></head><body><main>
@if(!($standalone ?? false))
<div class="toolbar"><a href="{{ route('home') }}">Pollmedia</a><form method="get"><label for="edition">Report edition</label> <select id="edition" name="edition"><option value="quarterly" @selected($edition==='quarterly')>Current quarter</option><option value="annual" @selected($edition==='annual')>Current year</option></select> <button type="submit">Generate draft</button></form><button type="button" onclick="window.print()">Print / save PDF</button><a class="button" href="{{ route('reports.pilibhit',['edition'=>$edition,'download'=>1]) }}">Download HTML</a>@if(auth()->user()?->is_admin)<form method="post" action="{{ route('reports.store') }}">@csrf<input type="hidden" name="edition" value="{{ $edition }}"><button type="submit">Save dated draft</button></form>@endif<a href="{{ route('reports.archive') }}">Saved drafts</a></div>
@endif
<p class="kicker">POLLMEDIA · DISTRICT RESEARCH DRAFT</p><h1>Pilibhit district<br>{{ $period }} · {{ ucfirst($edition) }} edition</h1><p>Generated {{ $generatedAt->format('d M Y, H:i') }} IST · Uttar Pradesh, India</p>
<p class="notice"><strong>Draft for review—not a published period-end report.</strong> This is a snapshot of currently accepted evidence assembled during {{ $period }}. Census figures and election results retain their original years; they do not measure activity or change during this quarter or year. Saved editions preserve the evidence available when each draft was generated.</p>
<section><h2>1. Election context</h2><p>Pilibhit district’s four ACs are shown alongside Pilibhit PC for context. The PC also includes Baheri AC in Bareilly district; PC results are not district totals. Winners and parties below refer to the election year, not a fresh officeholder verification.</p>
<div class="table"><table><thead><tr><th>Constituency</th><th>Election</th><th>Winner / party then</th><th>Winning margin</th></tr></thead><tbody>@forelse($contests as $entry)<tr><td>{{ $entry['place']->name }} {{ strtoupper($entry['place']->type) }}</td><td>{{ $entry['result']->year }}</td><td>{{ $entry['result']->winner->candidate_name }}<br><small>{{ $entry['result']->winner->party_at_election }}</small></td><td>{{ number_format($entry['result']->margin) }} votes</td></tr>@empty<tr><td colspan="4">Election results have not been imported.</td></tr>@endforelse</tbody></table></div></section>
<section><h2>2. Historical Census baseline</h2><div class="card stats"><div><strong>{{ number_format($census['district_population']) }}</strong>District population · Census 2011</div><div><strong>{{ number_format(count($census['villages'])) }}</strong>Available 2011 village profiles</div><div><strong>{{ number_format(count($historical['villages'])) }}</strong>Available 2001 village profiles</div></div><p>The population is the official 2011 district total, including urban areas. The 2001 workbook contains inhabited village profiles only. Different profile counts do not establish village growth, population growth or unchanged boundaries.</p><a href="{{ $census['source_url'] }}">Official 2011 Census workbook ↗</a></section>
<section><h2>3. Village connections and coverage</h2><p>Current directory snapshot: {{ $references['lgd-pilibhit']->retrieved_at }}. {{ number_format($lgd->count()) }} Pilibhit LGD village records are imported. Counts below cover the district’s entries in the imported electoral report.</p><div class="table"><table><thead><tr><th>Assembly constituency</th><th>LGD village mappings</th><th>Linked 2011 profiles</th></tr></thead><tbody>@foreach($coverage as $row)<tr><td>{{ $row['ac'] }}</td><td>{{ number_format($row['lgd_count']) }}</td><td>{{ number_format($row['profiles']) }}</td></tr>@endforeach</tbody></table></div><p><strong>{{ number_format($coverage->sum('profiles')) }} of {{ number_format(count($census['villages'])) }} Census 2011 profiles</strong> have code-based electoral matches. These are profile counts, not constituency population totals.</p>
@if($unmapped->isNotEmpty())<h3>Profiles awaiting an electoral match</h3><ul>@foreach($unmapped as $village)<li>{{ $village['name'] }} · Census code {{ $village['code'] }}</li>@endforeach</ul>@endif</section>
<section><h2>4. Information still needed</h2><ul><li>Verified current public-service measurements and village polling-part relationships.</li><li>Comparable measurements from two reporting dates before making quarterly or annual trend claims.</li><li>Editorial review and an archived final edition before publication.</li></ul><p>No automated narrative, village voting pattern or performance rating is inferred from missing data.</p></section>
<section><h2>Sources & references</h2>@foreach($references as $key=>$reference)<div class="card"><h3>{{ \Illuminate\Support\Str::headline($key) }}</h3><p>{{ $reference->publisher }} · Imported {{ substr($reference->retrieved_at,0,10) }} · Edition ID {{ $reference->id }}</p><a href="{{ $reference->url }}">Official source ↗</a><p class="small hash">File SHA-256: {{ $reference->sha256 ?? 'Not recorded' }}</p></div>@endforeach
@foreach($contests as $entry)<p><a href="{{ $entry['result']->url }}">ECI · {{ $entry['place']->name }} {{ strtoupper($entry['place']->type) }} · {{ $entry['result']->year }} ↗</a><br><small>{{ $entry['result']->source_locator }} · Imported {{ substr($entry['result']->retrieved_at,0,10) }}</small></p>@endforeach</section>
<footer>Pollmedia · Local research pilot · Draft assembled from accepted source editions. <a href="{{ route('sources.index') }}">Source status</a></footer></main></body></html>
