@extends('seo-layout')
@section('content')
<h1>Constituency map review</h1><p>Checks cover source geometry, missing or duplicate identifiers, historical boundaries and state groupings. Public names remain normal; approximate geography is explained in the map disclaimer. Acknowledging a flag records evidence without certifying or altering a boundary.</p>
<div class="card"><form method="get" class="filters"><label>State / UT<select name="state">@foreach($catalogue['states'] as $entry)<option value="{{ $entry['slug'] }}" @selected($entry['slug']===$state['slug'])>{{ $entry['name'] }}</option>@endforeach</select></label><label>Type<select name="kind"><option value="">Both</option><option value="pc" @selected(request('kind')==='pc')>Lok Sabha · PC</option><option value="ac" @selected(request('kind')==='ac')>Assembly · AC</option></select></label><button>Show checks</button></form><p>{{ $items->total() }} flagged source records in this selection. <a href="{{ route('site.manage') }}">Edit party colours →</a> · <a href="{{ route('site.editor') }}">Election data corrections →</a></p></div>
@foreach($items as $feature) @php $p=$feature['properties'];$review=$reviews[$state['sha256'].':'.$feature['id']]??null; @endphp
<article class="card"><h2>{{ $p['name'] ?: 'Name absent from source' }} · {{ strtoupper($p['kind']) }} {{ $p['code'] }}</h2><p>{{ $feature['id'] }} · {{ $review?'Acknowledged':'Needs review' }}</p><ul>@foreach($p['review_notes'] as $note)<li>{{ $note }}</li>@endforeach</ul>@if($p['geometry_warning'])<p>{{ $p['geometry_warning'] }}</p>@endif
<details><summary>Original attributes & source hash</summary><p class="url">{{ $state['sha256'] }}</p><pre class="url">{{ json_encode($p['source_attributes'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details>
@if($review)<p>{{ $review['note'] }} · {{ $review['at'] }}</p>@if($review['evidence_url'])<a href="{{ $review['evidence_url'] }}" target="_blank" rel="noopener">Review evidence ↗</a>@endif @endif
<form method="post" action="{{ route('elections.maps.review-save') }}" data-manual-submit>@csrf<input type="hidden" name="state" value="{{ $state['slug'] }}"><input type="hidden" name="feature" value="{{ $feature['id'] }}"><input type="hidden" name="hash" value="{{ $state['sha256'] }}"><label class="field">Review / correction note<textarea name="reason" rows="3" required minlength="10" maxlength="2000"></textarea></label><label class="field">Official evidence URL (optional)<input type="url" name="evidence_url" maxlength="2000"></label><button>Record acknowledgement</button></form></article>
@endforeach
{{ $items->links() }}
@endsection
