@extends('seo-layout')
@section('content')
<a href="{{ route('election-batches.index') }}">All statewide batches</a>
<h1>{{ $record->state }} / {{ $record->year }} Assembly import</h1>
<section class="card"><h2>Status: {{ str_replace('_',' ',$record->status) }}</h2><p>{{ $record->ready_count }} validated · {{ $record->invalid_count }} need correction · expected coverage: 403 constituencies.</p><p><a href="{{ $record->source_url }}" target="_blank" rel="noreferrer">Official ECI report edition</a></p><p>Extraction does not publish results or change current representatives. A validated row confirms that its report figures reconcile; it still needs a verified constituency mapping and publication review.</p>
@if(in_array($record->status,['queued','processing']))<p>Background processing is pending or running. Refresh this page to see progress.</p><p class="muted">The imports queue needs a running application worker.</p><a href="{{ route('election-batches.show',$record->id) }}">Refresh batch</a>@endif
@if($record->error)<p role="alert">{{ $record->error }}</p>@endif
@if($record->status==='failed')<form method="post" action="{{ route('election-batches.retry',$record->id) }}">@csrf<button>Retry failed batch</button></form>@endif
<details><summary>Source checksums and processing dates</summary><p style="overflow-wrap:anywhere">Detailed: {{ $record->detail_sha256 }}<br>Summary: {{ $record->summary_sha256 }}</p><p>Started: {{ $record->started_at ?? 'Not started' }} / finished: {{ $record->finished_at ?? 'Not finished' }} UTC</p></details></section>
<section class="card"><h2>Statewide publication</h2>
@if($record->published_at)<p>Published {{ $record->published_at }} UTC by administrator #{{ $record->published_by }}. {{ $record->ready_count }} validated seats are linked to local public pages; {{ $record->invalid_count }} seats remain withheld.</p><a href="{{ route('states.show',['state'=>'uttar-pradesh','type'=>'ac']) }}#politics">Browse published Assembly constituencies →</a>
@elseif(in_array($record->status,['ready','needs_attention']) && $record->ready_count>0)
<p>Publish {{ $record->ready_count }} validated constituencies from the {{ $record->year }} edition using ECI’s Uttar Pradesh AC codes and names. Existing matching pages and results are preserved. Published results include candidate tables, vote shares, margins and official sources. District, PC, boundary and current MLA links require their own verified evidence.</p>
<form method="post" action="{{ route('election-batches.publish',$record->id) }}">@csrf<label><input type="checkbox" name="reviewed" value="1" required> I reviewed the official edition, validated coverage and withheld rows for local publication.</label><button>Publish {{ $record->ready_count }} validated constituencies</button></form>
@endif</section>
@if($options->isNotEmpty())<section class="card"><h2>Inspect a constituency</h2><form method="get" action="{{ route('election-batches.show',$record->id) }}"><label for="code">Assembly constituency</label><select id="code" name="code" required><option value="">Select a constituency</option>@foreach($options as $option)<option value="{{ $option->code }}" @selected(($input['code'] ?? null)==$option->code)>{{ $option->code }} / {{ $option->name }}</option>@endforeach</select><button>Show candidate table</button></form>
@if($selected)<h3>{{ $selected->code }} / {{ $selected->name }} — {{ $selected->status }}</h3>
@if($selected->error)<p role="alert">{{ $selected->error }}</p>@endif
@if($payload && $selected->status==='ready')<p>Electors: {{ number_format($payload['electors']) }} / votes polled: {{ number_format($payload['votes_polled']) }} / valid candidate votes: {{ number_format($payload['valid_candidate_votes']) }}</p><p>{{ $payload['source_locator'] }}</p><div style="overflow:auto"><table><thead><tr><th>Candidate</th><th>Party at election</th><th>General votes</th><th>Postal votes</th><th>Total</th></tr></thead><tbody>@foreach($payload['candidates'] as $candidate)<tr><td>{{ $candidate['candidate_name'] }}</td><td>{{ $candidate['party_at_election'] }}</td><td>{{ number_format($candidate['general_votes']) }}</td><td>{{ number_format($candidate['postal_votes']) }}</td><td>{{ number_format($candidate['votes']) }}</td></tr>@endforeach</tbody></table></div>
@if($selected->place_id)<p><a href="{{ route('places.show',['type'=>'ac','slug'=>substr(\Illuminate\Support\Facades\DB::table('places')->where('id',$selected->place_id)->value('slug'),3),'year'=>$record->year]) }}#elections">Open published election page →</a></p>@endif
@if($mapped)<form method="post" action="{{ route('election-batches.review',[$record->id,$selected->code]) }}">@csrf<p>This code and source edition match an existing Pollmedia constituency. Open its change preview before publishing.</p><button>Create publication review</button></form>@elseif(!$selected->place_id)<p>Publication mapping pending. This constituency has not yet been linked to a verified Pollmedia place.</p>@endif
@endif
@endif
</section>@endif
<section class="card"><h2>Constituency validation</h2><form method="get"><label for="status">Filter</label><select name="status" id="status"><option value="">All rows</option><option value="ready" @selected(($input['status'] ?? '')==='ready')>Validated</option><option value="invalid" @selected(($input['status'] ?? '')==='invalid')>Needs correction</option></select><button>Filter</button></form>
<div style="overflow:auto"><table><thead><tr><th>Code</th><th>Constituency</th><th>Validation</th><th>Issue</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->code }}</td><td><a href="{{ route('election-batches.show',[$record->id,'code'=>$row->code]) }}">{{ $row->name }}</a></td><td>{{ $row->status==='ready' ? 'Validated' : 'Needs correction' }}</td><td>{{ $row->error ?? 'Figures reconcile' }}</td></tr>@empty<tr><td colspan="4">No rows available for this filter.</td></tr>@endforelse</tbody></table></div>{{ $rows->links() }}</section>
@endsection
