<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex">
<title>{{ $selected['name'] }} · {{ $data['year'] }} {{ strtoupper($kind) }} result report · Pollmedia</title>
<style>
body{max-width:900px;margin:2rem auto;padding:0 1rem;color:var(--palette-173d37);font:15px/1.5 system-ui,sans-serif}a{color:var(--palette-176c55)}h1{line-height:1.2}header,footer{border-bottom:1px solid var(--palette-b8cabd);padding-bottom:1rem}footer{border-top:1px solid var(--palette-b8cabd);border-bottom:0;margin-top:2rem;padding-top:1rem}.notice{background:var(--palette-fff8e8);border-left:4px solid var(--palette-c9ab69);padding:.75rem 1rem}table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid var(--palette-b8cabd);padding:.5rem;text-align:left;vertical-align:top}th{background:var(--palette-e4ede1)}.numbers{display:flex;gap:2rem;flex-wrap:wrap}.numbers p{margin:.5rem 0}.small{font-size:.85rem}.actions{display:flex;gap:1rem;flex-wrap:wrap}@media print{body{margin:0;max-width:none}.actions{display:none}a{color:inherit;text-decoration:none}tr{break-inside:avoid}}
</style>
<script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script>@include('site-theme')</head>
<body>
@php $multiSeat = ($selected['number_of_seats'] ?? 1) > 1; @endphp
<header><strong>Pollmedia · historical election result</strong><h1>{{ $selected['name'] }}</h1><p>{{ $data['year'] }} {{ $kind === 'pc' ? 'Lok Sabha' : 'Assembly' }} election · {{ $state }} · Official constituency code: {{ $selected['official_pc_code'] ?? $selected['official_ac_code'] ?? ($kind === 'ac' ? $selected['code'] : 'Not reported') }}</p><p class="actions"><button type="button" onclick="window.print()">Print or save as PDF</button><a href="{{ route($kind === 'pc' ? 'elections.history' : 'elections.assembly', ['edition' => $edition, 'state' => $state, 'code' => $selected['code']]) }}">View online result</a><a href="{{ route('feedback.create',['path'=>route($kind === 'pc' ? 'elections.history' : 'elections.assembly', ['edition' => $edition, 'state' => $state, 'code' => $selected['code']], false),'category'=>'data']) }}">Report a problem</a></p></header>
@include('printable-election-map',['printMapState'=>$state,'printMapSeat'=>$selected['name'],'printMapResult'=>$selected['display_result']??[],'printMapYear'=>$data['year']])
<p class="notice">This report reproduces one constituency table from the cited historical edition. Names and boundaries belong to that election. It does not establish a match with a present-day constituency or complete national coverage.</p>
@if($multiSeat)<p class="notice">This constituency elected {{ $selected['number_of_seats'] }} members. The reported vote total can include votes for more than one seat, so it is not ordinary one-seat turnout. Confirm elected members separately in the official report.</p>@endif
@if($selected['has_warning'])<p class="notice"><strong>† Data note:</strong> {{ $selected['error'] ?? 'This record requires review.' }} @if(($selected['source_discrepancy']['field']??'')==='votes_polled')Detailed votes polled: {{ number_format($selected['source_discrepancy']['detail_value']) }}; official summary: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @endif @if(($selected['source_discrepancy']['field']??'')==='reported_total')Workbook total: {{ number_format($selected['source_discrepancy']['workbook_value']) }}; candidate rows and official summary: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @elseif(($selected['source_discrepancy']['field']??'')==='candidate_total')Candidate rows: {{ number_format($selected['source_discrepancy']['candidate_sum']) }}; official summary: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @elseif(($selected['source_discrepancy']['field']??'')==='elector_components')Source elector components: {{ number_format($selected['source_discrepancy']['component_value']) }}; official summary total: {{ number_format($selected['source_discrepancy']['summary_value']) }}. @endif @if(isset($selected['summary_totals']['valid_candidate_votes'],$selected['valid_candidate_votes']) && $selected['summary_totals']['valid_candidate_votes']!==$selected['valid_candidate_votes'] && ($selected['source_warning_code']??'')!=='workbook_pdf_summary')Detailed candidate votes: {{ number_format($selected['valid_candidate_votes']) }}; report summary: {{ number_format($selected['summary_totals']['valid_candidate_votes']) }}. @endif @if($selected['display_result']['derived'] ?? false)The winner and margin use the detailed candidate votes. @endif Check the official report for the original figures.</p>@elseif($selected['review'])<p>Reviewed result. Source references remain below.</p>@endif
@foreach($selected['edition_notes'] ?? [] as $note)<p class="notice">{{ $note }}</p>@endforeach
@php
    $summaryVoteLabel = $multiSeat ? 'Valid candidate votes across seats' : (($selected['source_warning_code'] ?? '') === 'workbook_pdf_summary'
        ? (isset($selected['summary_totals']['nota_votes']) ? 'Valid candidate votes' : 'Source valid votes (including NOTA)')
        : (in_array($selected['source_warning_code'] ?? '', ['summary_turnout_with_detail_warnings', 'summary_only_turnout'], true)
            ? 'Valid votes (official summary)' : 'Valid candidate votes'));
    $polledLabel = $multiSeat ? 'Source votes polled across seats' : 'Votes polled';
@endphp
<div class="numbers">@foreach(['electors' => 'Electors', 'votes_polled' => $polledLabel, 'valid_candidate_votes' => $summaryVoteLabel] as $key => $label)@php $value = $selected[$key] ?? null; if ($key === 'votes_polled' && ($selected['source_discrepancy']['field'] ?? '') === 'votes_polled') $value = $selected['summary_totals'][$key] ?? $value; if ($key === 'valid_candidate_votes' && in_array($selected['source_warning_code'] ?? '', ['workbook_pdf_summary', 'summary_turnout_with_detail_warnings', 'summary_only_turnout'], true)) $value = $selected['summary_totals'][$key] ?? null; @endphp<p><strong>{{ $label }}:</strong> {{ ($selected['display_result']['uncontested'] ?? false) && $value === 0 ? 'Not reported (uncontested)' : ($value !== null ? number_format($value) : 'Not reported') }}</p>@endforeach</div>
@if($selected['display_result'])<p><strong>Winner:</strong> {{ $selected['display_result']['winner'] }}{{ $selected['has_warning'] ? ' †' : '' }} @if($selected['display_result']['uncontested'] ?? false) · Uncontested; no poll or winning margin @else · <strong>Margin:</strong> {{ number_format($selected['display_result']['margin']) }} votes{{ $selected['has_warning'] ? ' †' : '' }} @endif</p>@endif
@if(!$selected['display_result'])<p class="notice">* @if(!empty($selected['candidates']))Available candidate rows are shown as recorded.@else Candidate rows could not be extracted reliably.@endif @if($multiSeat)This multi-seat constituency has no single winner or ordinary one-seat turnout. @if(!empty($selected['display_multi_seat_winners']))The official summary declares the elected members listed below; no one-seat margin is reported.@elseif(!empty($selected['display_multi_seat_reviewed_declarations']))The official summary names members listed below, but the declaration remains under review.@else Its elected members need separate verification.@endif @else A winner has not been confirmed from this table.@endif <a href="{{ $data['source_url'] }}">Check the official report ↗</a></p>@endif
@if($multiSeat && !empty($selected['display_multi_seat_winners']))<h2>Source-declared elected members</h2><ul>@foreach($selected['display_multi_seat_winners'] as $member)<li>{{ $member['name'] }} ({{ $member['party'] }}) · {{ number_format($member['votes']) }} candidate votes</li>@endforeach</ul>@endif
@if($multiSeat && !empty($selected['display_multi_seat_reviewed_declarations']))<h2>Members named in the official summary (under review)</h2><p class="notice">@if($selected['display_multi_seat_reviewed_declarations']['reason'] === 'incomplete_official_list')The summary names {{ count($selected['display_multi_seat_reviewed_declarations']['members']) }} of {{ $selected['display_multi_seat_reviewed_declarations']['seats'] }} members; the remaining seat is not identified there.@else The summary names both members, but duplicate candidate rows conflict with the official vote total.@endif PDF page {{ $selected['summary_page'] }} · <a href="{{ $data['source_url'] }}">Official report</a></p><ul>@foreach($selected['display_multi_seat_reviewed_declarations']['members'] as $member)<li>{{ $member['name'] }} ({{ $member['party'] }}) · {{ number_format($member['votes']) }} votes reported in the summary</li>@endforeach</ul>@endif
<table><caption>Candidate votes as recorded in the selected report edition</caption><thead><tr><th>Candidate</th><th>Party at election</th><th>General / EVM votes</th><th>Postal votes</th><th>Total votes</th></tr></thead><tbody>
@forelse($selected['candidates'] as $candidate)<tr><td>{{ $candidate['candidate_name'] }}</td><td>{{ $candidate['party_at_election'] }}</td>@foreach(['general_votes', 'postal_votes', 'votes'] as $key)<td>{{ ($selected['display_result']['uncontested'] ?? false) && ($candidate[$key] ?? null) === 0 ? 'Not reported' : (isset($candidate[$key]) ? number_format($candidate[$key]) : 'Not reported') }}</td>@endforeach</tr>
@empty<tr><td colspan="5">Candidate rows could not be extracted reliably. Consult the official source.</td></tr>@endforelse
</tbody></table>
<h2>Source and provenance</h2><p><a href="{{ $data['source_url'] }}">Official election report edition</a></p>@if(!empty($selected['summary_result_source_url']))<p><a href="{{ $selected['summary_result_source_url'] }}">ECI constituency summary</a></p>@endif<p class="small">Archive edition: {{ $edition }} · Source SHA-256: {{ $data['source_sha256'] }} · @isset($selected['detail_page'])Detailed table: PDF page {{ $selected['detail_page'] }} · @endisset {{ $selected['source_locator'] ?? '' }}</p>
@foreach($data['additional_sources'] ?? [] as $source)@if(! empty($source['source_url']))<p class="small"><a href="{{ $source['source_url'] }}">Additional official source: {{ $source['name'] }}</a></p>@endif @endforeach
<footer>Pollmedia research report · Generated {{ now('Asia/Kolkata')->format('d M Y, H:i') }} IST · Figures remain attributed to their original election year.</footer>
</body></html>
