@extends('seo-layout')
@section('content')
<p class="admin-eyebrow">Published listings / {{ ucfirst($section) }}</p>
<h1>{{ ucfirst($section) }} listing editor</h1>
<p>Select a listing to edit the data used by its public tables, graphs and representative card. Calculated totals and winners update from the underlying figures.</p>
<form method="get" data-manual-submit class="filters">
@if($section==='elections')<label>Listing type<select name="kind" onchange="this.form.querySelectorAll('[name=state],[name=year]').forEach(input=>input.value='');this.form.submit()"><option value="pc" @selected(($input['kind']??'pc')==='pc')>Lok Sabha / PC</option><option value="ac" @selected(($input['kind']??'pc')==='ac')>Assembly / AC</option></select></label><label>State<select name="state" onchange="this.form.querySelectorAll('[name=year]').forEach(input=>input.value='');this.form.submit()"><option value="">All states</option>@foreach($states as $state)<option @selected(($input['state']??'')===$state)>{{ $state }}</option>@endforeach</select></label>@endif
@if($years->isNotEmpty())<label>Year<select name="year"><option value="">All years</option>@foreach($years as $year)<option @selected((string)($input['year']??'')===(string)$year)>{{ $year }}</option>@endforeach</select></label>@endif
<label>Listing name<input name="q" value="{{ $input['q']??'' }}" placeholder="{{ $section==='elections'?'Amethi, Lucknow…':'Search place or polling part' }}"></label><button>Find listings</button></form>
@if($documents->isEmpty())<section class="card admin-listing-card"><div class="admin-card-heading"><div><p class="admin-eyebrow">Listing directory</p><h2>Choose a listing</h2></div><span class="admin-count-badge">{{ number_format($records->total()) }} {{ \Illuminate\Support\Str::plural('listing',$records->total()) }}</span></div><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Listing</th><th>Area / type</th><th>Year</th><th class="admin-action-heading">Action</th></tr></thead><tbody>@forelse($records as $record)<tr><td><strong class="admin-record-name">{{ $record->constituency_name??$record->name }}</strong><small class="admin-record-hint">{{ $section==='elections'?'Election constituency':($section==='census'?'Census record':'SIR polling part') }}</small></td><td>{{ isset($record->state_label)?\Illuminate\Support\Str::title($record->state_label):($record->level??'Polling part') }} @if(isset($record->kind))<span class="admin-type-badge">{{ strtoupper($record->kind) }}</span>@endif</td><td>{{ $record->year??'SIR' }} @if(isset($record->available_years))<small class="admin-record-hint">{{ $record->available_years }} available years</small>@endif</td><td class="admin-table-action"><a class="admin-edit-link" href="{{ route('listings.index',['section'=>$section]+request()->except('page','id')+['id'=>$record->id]) }}">Edit complete listing <span aria-hidden="true">→</span></a></td></tr>@empty<tr><td colspan="4">No matching listings.</td></tr>@endforelse</tbody></table></div><div class="admin-table-footer">{{ $records->links() }}</div></section>@endif
@foreach($warnings as $warning)<p class="notice">{{ $warning }}</p>@endforeach
@foreach($documents as $document)
<section class="card admin-listing-card"><div class="admin-card-heading"><div><p class="admin-eyebrow">Listing details & source evidence</p><h2>{{ $document['label'] }}</h2></div><span class="admin-type-badge">{{ ucfirst($section) }}</span></div><p><a href="{{ $document['public'] }}" target="_blank" rel="noopener">View public listing ↗</a> @if($document['source']) · <a href="{{ $document['source'] }}" target="_blank" rel="noopener">Official source ↗</a>@endif @if($document['archive']) · <a href="{{ route('election-archives.extraction',[$document['archive'],'code'=>$document['fields']['code']]) }}">Original report and source documents</a>@endif</p>
<form class="listing-fields" method="post" action="{{ route('listings.save') }}">@csrf
<input type="hidden" name="table" value="{{ $document['table'] }}"><input type="hidden" name="id" value="{{ $document['id'] }}"><input type="hidden" name="expected" value="{{ $document['expected'] }}"><input type="hidden" name="record" value="{{ json_encode($document['fields']) }}">
@include('listing-fields',['fields'=>$document['fields'],'path'=>[],'readonly'=>$document['readonly']])
<label>Official reference link<input name="reference_url" type="url" value="{{ $document['source'] }}"></label><label>Correction reason<textarea name="reason" minlength="5" maxlength="2000" required></textarea></label><button>Save and update public listing</button></form>
<h3>Reference PDFs, Excel and CSV</h3>@foreach($document['attachments'] as $attachment)<p><a href="{{ route('listings.file',['key'=>$attachment->key]) }}">{{ json_decode($attachment->value,true)['name'] }}</a></p>@endforeach
<form method="post" enctype="multipart/form-data" action="{{ route('listings.attach') }}">@csrf<input type="hidden" name="table" value="{{ $document['table'] }}"><input type="hidden" name="id" value="{{ $document['id'] }}"><input type="file" name="file" accept=".pdf,.xlsx,.xls,.csv" required><button>Attach reference file</button></form>
</section>@endforeach
<script>
document.querySelectorAll('.listing-fields').forEach(form=>form.addEventListener('submit',()=>{const record=JSON.parse(form.querySelector('[name=record]').value);form.querySelectorAll('[data-field-path]').forEach(input=>{const path=JSON.parse(input.dataset.fieldPath);let target=record;path.slice(0,-1).forEach(key=>target=target[key]);let value=input.value;if(input.dataset.type==='boolean')value=value==='true';else if(input.dataset.type==='number')value=value===''?null:Number(value);else if(input.dataset.type==='null')value=value===''?null:(Number.isFinite(Number(value))?Number(value):value);target[path[path.length-1]]=value;});form.querySelector('[name=record]').value=JSON.stringify(record);}));
</script>
@endsection
