<!doctype html>
<html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
@include('seo-metadata', ['canonical'=>route('home'),'seoTitle'=>'India, elections & places · Pollmedia','seoDescription'=>'Explore Lok Sabha and Assembly election trends, state results, Census and places.','breadcrumbs'=>['India'=>route('home')]])
@include('site-theme')
<link rel="stylesheet" href="{{ asset('css/election-dashboard.css') }}?v={{ substr(hash_file('sha256',public_path('css/election-dashboard.css')),0,12) }}">
<link rel="stylesheet" href="{{ asset('css/home-dashboard.css') }}?v={{ substr(hash_file('sha256',public_path('css/home-dashboard.css')),0,12) }}">
<script src="{{ asset('js/history-lines.js') }}?v={{ substr(hash_file('sha256',public_path('js/history-lines.js')),0,12) }}" defer></script>
<script src="{{ asset('js/home-dashboard.js') }}?v={{ substr(hash_file('sha256',public_path('js/home-dashboard.js')),0,12) }}" defer></script>
</head><body class="election-ui home-dashboard">@include('public-header')
<main class="home-main">
<section class="home-hero"><div><p class="home-eyebrow">India, across the years</p><h1>See how India votes.<br>Explore the places behind the numbers.</h1><p>Election trends, constituency results and the story of your place.</p><nav class="home-topics" aria-label="Explore topics"><a href="#lok-sabha">Lok Sabha elections ↓</a><a href="#assembly">Assembly elections ↓</a><a href="#census-places">Census & places ↓</a></nav></div><div class="home-hero-mark" aria-hidden="true"><span>Votes.</span><span>People.</span><span>Places.</span></div></section>
<section class="home-finder" aria-labelledby="finder-title"><div><p class="home-eyebrow">Go straight to your constituency</p><h2 id="finder-title">Find election results</h2></div><form data-home-finder data-endpoint="{{ route('home') }}"><label>Election<select name="kind"><option value="pc">Lok Sabha</option><option value="ac">State Assembly</option></select></label><label>State / Union Territory<select name="state"><option value="">Choose a state</option>@foreach($states as $item)<option value="{{ $item['name'] }}">{{ $item['name'] }}</option>@endforeach</select></label><label>Constituency<select name="seat" disabled><option value="">Choose a state first</option></select></label><button disabled>View results →</button><p class="home-finder-status" role="status"></p></form></section>
@foreach(['pc'=>['lok-sabha','Lok Sabha elections','India’s parliamentary election history'], 'ac'=>['assembly','Assembly elections','How the states have voted']] as $kind=>[$anchor,$label,$description])
@php
 $section=$electionDashboard[$kind];
 $compact=fn($value)=>$value>=10000000?rtrim(rtrim(number_format($value/10000000,1),'0'),'.').' Cr.':($value>=100000?rtrim(rtrim(number_format($value/100000,1),'0'),'.').' L':number_format($value));
 $plots=[['title'=>'Voter turnout across the years','unit'=>'%','series'=>[['key'=>'turnout','label'=>'Turnout']]],['title'=>'Votes polled and registered electors','unit'=>'people','series'=>[['key'=>'polled','label'=>'Votes polled'],['key'=>'electors','label'=>'Registered electors']]],['title'=>'Top five parties · vote share over time','unit'=>'%','series'=>array_map(fn($party,$i)=>['key'=>'party'.$i.'_share','votes_key'=>'party'.$i,'label'=>$party],$section['top_parties'],array_keys($section['top_parties']))]];
@endphp
<section id="{{ $anchor }}" class="home-election-section"><header class="home-section-heading"><div><p class="home-eyebrow">{{ $kind==='pc'?'01 · Parliament':'02 · State legislatures' }}</p><h2>{{ $label }}</h2><p>{{ $description }}</p></div><a class="home-text-link" href="{{ route($kind==='pc'?'elections.history':'elections.assembly') }}">Explore all results →</a></header>
<div class="home-stat-grid">@foreach(['elections'=>$kind==='pc'?'Election years available':'State elections available','parties'=>'Parties with recorded votes','candidates'=>'Candidate entries','results'=>'Constituency results'] as $key=>$statLabel)<article><span>{{ $statLabel }}</span><strong>{{ $section['rows']?$compact($section['stats'][$key]):'—' }}</strong></article>@endforeach</div>
@if($section['rows'])<div class="home-chart-grid">@foreach($plots as $plot)@include('home-history-chart',['plot'=>$plot,'chartRows'=>$section['rows']])@endforeach</div>
<p class="home-chart-note">{{ $kind==='ac'?'Assembly figures combine state elections held in the same calendar year. ':'' }}Figures reflect available source records. Turnout uses votes and electors from the same available constituencies. Party shares use available candidate votes; the five parties are ranked by their total votes across the displayed years. † Source notes apply.</p>
@else<p class="home-empty">Explore state pages for available election results and original sources.</p>@endif
<div class="home-section-heading home-state-heading" @if($kind==='pc') id="states" @endif><div><h3>Explore {{ $kind==='pc'?'Lok Sabha':'Assembly' }} by state</h3><p>Choose a state to see its map, trends and constituencies.</p></div><label class="home-state-filter">Find a state<input type="search" placeholder="State name" data-state-filter="{{ $kind }}"></label></div>
<div class="home-state-grid" data-state-grid="{{ $kind }}">@foreach($states->filter(fn($item)=>$kind==='pc' || $item['kind']==='State' || in_array($item['slug'],['delhi','jammu-and-kashmir','puducherry'])) as $item)<a class="home-state-card" href="{{ route('states.show',['state'=>$item['slug']]) }}#{{ $kind }}-history"><div><span>{{ $item['kind'] }}</span><strong>{{ $item['name'] }}</strong></div><span class="home-card-arrow" aria-hidden="true">↗</span></a>@endforeach</div><p data-state-empty="{{ $kind }}" hidden>No matching states.</p>
</section>
@endforeach
<section id="census-places" class="home-census-section"><div><p class="home-eyebrow">03 · People & places</p><h2>Census & places</h2><p>Explore population, households, literacy and work for your place.</p></div><div class="home-census-links"><a href="{{ route('civic.index') }}">Explore Census & places →</a><a href="{{ route('villages.index') }}">Find a village →</a></div></section>
</main>@include('public-footer')</body></html>
