<!doctype html>

<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/vendor/maplibre/maplibre-gl.css">

@include('seo-metadata', ['canonical' => $state ? route('states.show', ['state' => $state]) : route('home'), 'seoTitle' => $title.' · Elections & places · Pollmedia', 'seoDescription' => 'Explore available election results, constituency pages and district data, with official sources and clear coverage dates.', 'breadcrumbs' => $state ? ['India' => route('home'), $title => route('states.show', ['state' => $state])] : ['India' => route('home')]])

<style>

*{box-sizing:border-box}body{margin:0;background:#f5f6f0;color:#173d37;font:15px/1.6 system-ui,sans-serif}a{color:#176c55;text-underline-offset:4px}header{background:#123d35;padding:20px 5vw;display:flex;justify-content:space-between}header a{color:#def1e4;text-decoration:none}.brand{font-size:27px;font-weight:750}header nav{display:flex;gap:24px;align-items:center}main{max-width:1220px;margin:auto;padding:40px 24px}h1{font-size:64px;line-height:1.1;letter-spacing:-2px;margin:16px 0}h2{font-size:27px;margin:6px 0 18px}h3{margin:8px 0}p{color:#65766c}.kicker{font-size:11px;text-transform:uppercase;letter-spacing:1.6px;font-weight:700}.hero{display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:center}.map{height:330px;border-radius:14px;overflow:hidden;border:1px solid #dce5dc}.small{font-size:12px}.notice{background:#fff8e8;border-left:3px solid #c9ab69;padding:12px 18px;margin:24px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:white;border:1px solid #dce5dc;border-radius:10px;padding:22px;min-width:0}section{margin:36px 0;scroll-margin-top:20px}.search{display:flex;flex-wrap:wrap;align-items:end;gap:14px;margin:20px 0}label{display:block;font-size:12px;margin-bottom:5px}input,select,button{font:inherit;padding:11px 14px;border:1px solid #b8cabd;border-radius:6px}input{width:min(350px,75vw)}button,.button{background:#176c55;color:white;border:0;cursor:pointer}.button{display:inline-block;text-decoration:none;padding:10px 16px;border-radius:6px}.tag{font-size:11px;background:#e4ede1;padding:4px 9px;border-radius:4px}footer{border-top:1px solid #dce5dc;padding-top:20px;font-size:12px;color:#65766c}@media(max-width:760px){.hero,.grid{grid-template-columns:1fr}h1{font-size:48px}header nav{gap:12px;font-size:12px}.map{height:270px}}



.home{background:radial-gradient(ellipse at 12% 10%,#e4efdf 0,transparent 36%),#f6f7f1}.home main{padding-top:52px}.home .hero{gap:48px}.home .hero h1{font-size:clamp(44px,5.7vw,72px);letter-spacing:-3px;line-height:1.04;margin:22px 0}.home .hero h1 em{font-style:normal;color:#258368}.intro{font-size:18px;line-height:1.7;max-width:570px}.hero-actions{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:24px 0}.home .button{padding:13px 22px;border-radius:8px;box-shadow:0 5px 14px #176c5518}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:7px 12px;background:#e2eddf;border:1px solid #ccddc8;border-radius:30px;font-size:11px;letter-spacing:1px;text-transform:uppercase}.eyebrow:before{content:'';width:7px;height:7px;background:#258368;border-radius:50%}.map-shell{background:white;border:1px solid #dce5dc;border-radius:20px;padding:14px;box-shadow:0 18px 50px #173d3710;transform:rotate(1deg)}.map-shell .map{height:320px;border-radius:12px}.map-caption{padding:0 9px}.map-caption strong{display:block;font-size:14px;margin-top:10px}.map-caption p{margin:5px 0}.value-strip{display:flex;flex-wrap:wrap;gap:12px 24px;margin-top:24px;font-size:12px;color:#4d6e62}.value-strip span:before{content:'✓';color:#258368;font-weight:800;margin-right:7px}.purpose{margin-top:50px}.section-top{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:22px}.section-top h2{margin-bottom:0}.section-top p{max-width:420px;margin:0}.feature{position:relative;padding:28px;border-top:3px solid #258368;transition:transform .18s,box-shadow .18s}.feature:hover{transform:translateY(-3px);box-shadow:0 10px 28px #173d3710}.feature-number{display:flex;width:38px;height:38px;background:#e4ede1;align-items:center;justify-content:center;border-radius:10px;font-size:13px;font-weight:750;margin-bottom:22px}.feature h3{font-size:21px;letter-spacing:-.5px}.feature p{min-height:78px}.feature a{font-weight:650;font-size:13px}.home .notice{border-radius:0 9px 9px 0;font-size:13px}.home #politics .search{background:#e9efe4;border-radius:12px;padding:22px}.home .card{border-radius:12px}.about-note{background:#173d37;border-radius:14px;padding:25px 30px;display:flex;gap:30px;align-items:center;margin:24px 0}.about-note h3{color:#eff6e9;min-width:210px;font-size:19px}.about-note p{color:#c5d9cb;margin:0;font-size:14px}.home a:focus-visible,.home button:focus-visible,.home input:focus-visible,.home select:focus-visible{outline:3px solid #d5a448;outline-offset:4px}@media(max-width:760px){.home main{padding-top:30px}.home .hero{gap:25px}.home .hero h1{letter-spacing:-2px}.map-shell{transform:none}.section-top,.about-note{display:block}.section-top p{margin-top:12px}.about-note h3{margin-top:0}.feature p{min-height:0}.intro{font-size:16px}.home #politics .search{padding:15px}.search select{max-width:100%}.search>div{max-width:100%}}@media(prefers-reduced-motion:reduce){.feature{transition:none}.feature:hover{transform:none}}

.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:30px 0}.summary div{background:#e4ede1;border-radius:10px;padding:18px}.summary strong{display:block;font-size:30px;line-height:1.15}.summary span{font-size:12px;color:#526b61}.state-list{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.state-card{padding:17px}.state-card h3{font-size:16px}.state-card p{margin:5px 0}@media(max-width:900px){.summary{grid-template-columns:repeat(2,1fr)}.state-list{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.state-list{grid-template-columns:1fr}}
</style><link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256', public_path('css/election-dashboard.css')), 0, 12) }}"></head><body class="election-ui {{ $state ? 'state' : 'home' }}">@include('public-header')<div class="dashboard-shell page-without-sidebar"><main class="dashboard-main">

@if($state)

<div class="hero"><div><div class="kicker"><a href="{{ route('india') }}">India</a> / {{ $title }} · {{ $stateSummary['kind'] }}</div><h1>{{ $title }},<br>election by election.</h1><p>Explore available Assembly archives, constituencies, districts and official sources for {{ $title }}.</p><a class="button" href="#historical-results">Explore election results ↓</a></div><div><div class="map" id="overview-map" role="region" aria-label="{{ $title }} geographic context map"></div><p class="small" id="map-note">Geographic context only; constituency boundaries and data overlays are shown only where verified.</p></div></div>

@else

<section class="landing-hero"><div class="landing-copy"><span class="landing-eyebrow">INDIA'S ELECTIONS. THE RECORD BEHIND THE RESULT.</span><h1>India,<br><em>understand the vote.</em></h1><p class="landing-intro">Explore election results, compare turnout and party votes, and discover the history of a constituency—all with links to the source.</p><div class="hero-actions"><a class="button" href="{{ route('elections.constituencies') }}">Find your constituency →</a><a class="landing-secondary" href="#states">Explore by state ↓</a></div><p class="landing-trust">Historical records · Sortable tables · Source-linked reports</p></div><div class="landing-directory"><p class="kicker">Where would you like to start?</p><a href="{{ route('elections.history') }}"><span class="directory-number">01</span><span><strong>Lok Sabha</strong><small>Parliamentary elections, candidates & votes</small></span><span aria-hidden="true">↗</span></a><a href="{{ route('elections.assembly') }}"><span class="directory-number">02</span><span><strong>State Assembly</strong><small>Assembly results across available editions</small></span><span aria-hidden="true">↗</span></a><a href="{{ route('elections.by-election-results') }}"><span class="directory-number">03</span><span><strong>By-elections</strong><small>Available parliamentary & assembly contests</small></span><span aria-hidden="true">↗</span></a><a href="{{ route('elections.polling-stations') }}"><span class="directory-number">04</span><span><strong>Polling-station records</strong><small>Available Form 20 tables & official reports</small></span><span aria-hidden="true">↗</span></a></div></section>
<div class="landing-explainer"><span>Choose a state</span><span aria-hidden="true">→</span><span>Compare election years</span><span aria-hidden="true">→</span><span>Open a constituency</span><span aria-hidden="true">→</span><span>Read the result & source</span></div>
<section class="landing-data panel" aria-labelledby="home-data-title"><div class="section-top"><div><p class="kicker">Inside the available archive</p><h2 id="home-data-title">Start with the numbers.</h2><p>Explore state report coverage, then open the results behind it.</p></div><a class="button" href="#states">All states & Union Territories →</a></div><div class="data-overview"><div class="data-stat"><strong>{{ number_format($states->sum('archive_editions')) }}</strong><span>Listed Assembly report editions</span></div><div class="data-stat"><strong>{{ $states->where('archive_editions','>',0)->count() }}</strong><span>Current states / UTs with listed editions</span></div><div class="data-stat"><strong>{{ $states->count() }}</strong><span>States & Union Territories to explore</span></div></div><div class="table-scroll" tabindex="0" role="region" aria-label="State archive coverage"><table data-sortable><caption>All current states and Union Territories. Counts describe the source catalogue, not verified election results or national completeness.</caption><thead><tr><th scope="col">State</th><th scope="col" data-sort-type="number">Report editions</th><th scope="col" data-sort-type="number">Earliest listed year</th><th scope="col" data-sort-type="number">Latest listed year</th><th scope="col">Explore</th></tr></thead><tbody>@foreach($states as $item)<tr><th scope="row">{{ $item['name'] }}</th><td>{{ $item['archive_editions'] }}</td><td>{{ $item['archive_years']->min() ?? '—' }}</td><td>{{ $item['archive_years']->max() ?? '—' }}</td><td><a href="{{ route('states.show',['state'=>$item['slug']]) }}">Turnout & results →</a></td></tr>@endforeach</tbody></table></div><p class="small">Each result retains its year, official source and review notes. A missing Assembly catalogue entry does not mean an area has no election history.</p></section>
<section id="about" class="purpose"><div class="section-top"><div><div class="kicker">What is Pollmedia?</div><h2>Election results. Local context. Original evidence.</h2></div><p>Start with a place. Explore its elections, find its representatives and follow the evidence.</p></div><div class="grid"><article class="card feature"><span class="feature-number" aria-hidden="true">01</span><h3>Understand the vote</h3><p>Explore available election results: who won, their party, vote shares and the margin of victory.</p><a href="{{ route('elections.history') }}">Explore Lok Sabha results →</a></article><article class="card feature"><span class="feature-number" aria-hidden="true">02</span><h3>Know who represents you</h3><p>Find MPs, MLAs and district authorities in the available directories, with official links and verification dates.</p><a href="{{ route('geography.india') }}">Meet the representatives →</a></article><article class="card feature"><span class="feature-number" aria-hidden="true">03</span><h3>Get to know your area</h3><p>Connect constituencies and districts. Explore available Census measurements, village maps and local data.</p><a href="{{ route('census-catalogue.index') }}">Explore local information →</a></article></div><div class="about-note"><h3>See the information.<br>Check the source.</h3><p>Pollmedia is a research platform, not an official government portal. Official links sit alongside the data, and missing coverage is labelled so you can see what is available and what is still to come.</p></div></section>

@endif

<section id="historical-results"><div class="kicker">Historical election results</div><h2>Browse by election, state and constituency</h2><p><a class="button" href="{{ route('elections.constituencies') }}">Search historical constituencies →</a></p><p>The source-backed archives contain constituency tables beyond the linked place profiles below. They preserve each election's names and boundaries, and show warnings where figures need review. They are not yet a complete national constituency report directory.</p><div class="grid"><article class="card"><h3>Lok Sabha elections</h3><p>Choose an available parliamentary election edition, state and constituency for candidate votes and official sources.</p><a href="{{ route('elections.history') }}">Browse PC results →</a></article><article class="card"><h3>Assembly elections</h3><p>Choose an available state election edition and assembly constituency.</p><a href="{{ route('elections.assembly') }}">Browse AC results →</a></article><article class="card"><h3>By-elections</h3><p>Browse available PC and AC by-election results by year and state.</p><a href="{{ route('elections.by-election-results') }}">Browse by-election results →</a></article></div></section>

@if(!$state)
<section id="states"><div class="kicker">India election explorer</div><h2>States & Union Territories</h2><p>Open a state or UT for its available election archive. Constituency, district and village links appear as their source-backed relationships are published.</p><div class="state-list">@foreach($states as $item)<article class="card state-card"><span class="tag">{{ $item['kind'] }}</span><h3><a href="{{ route('states.show', ['state'=>$item['slug']]) }}">{{ $item['name'] }} →</a></h3><p class="small">{{ $item['archive_editions'] }} Assembly archive editions</p></article>@endforeach</div></section>
@else
<section id="states"><div class="kicker">{{ $stateSummary['kind'] }} summary</div><h2>{{ $title }} election coverage</h2><div class="grid"><article class="card"><h3>Published profiles</h3><p>{{ $coverage->get('pc',0) }} PC · {{ $coverage->get('ac',0) }} AC · {{ $coverage->get('district',0) }} district pages</p><a href="#politics">Browse linked places →</a></article><article class="card"><h3>Assembly archive</h3><p>{{ $stateSummary['archive_editions'] }} available editions @if($stateSummary['archive_years']->isNotEmpty()) · Years:  {{ $stateSummary['archive_years']->implode(', ') }}@endif</p>@if($stateSummary['archive_editions'])<a href="{{ route('elections.assembly-sources', ['state'=>$title]) }}">Browse {{ $title }} Assembly sources →</a>@else<p class="small">No Assembly statistical-report edition is currently indexed for this area.</p>@endif</article><article class="card"><h3>Lok Sabha archive</h3><p>Browse national editions, then choose {{ $title }} and a parliamentary constituency.</p><a href="{{ route('elections.history') }}">Open Lok Sabha results →</a></article></div></section>
@endif

<section id="administration"><div class="kicker">02 / Administration & development</div><h2>Understand the local area</h2><div class="grid"><article class="card"><h3>Districts & authorities</h3><p>Find available official directories and dated development measurements on district pages.</p><a href="{{ route('geography.india') }}">Explore district pages →</a></article><article class="card"><h3>Villages & urban wards</h3><p>Explore available Census records for population, households and local places. Geographic detail varies by source and year.</p><a href="{{ route('census-catalogue.index') }}">Explore Census records →</a></article><article class="card"><h3>Polling stations & parts</h3><p>Browse available polling-station tables and Form 20 reports. Each source retains its election year and review notes.</p><a href="{{ route('elections.polling-stations') }}">Explore polling-station records →</a></article></div></section>

<footer><a href="{{ route('sitemap') }}">Sitemap</a> · Pollmedia · Election history, places and official sources · Coverage is shown on each page.</footer></main></div>

@if($state)<script src="/vendor/maplibre/maplibre-gl.js"></script>@endif<script>

if(document.getElementById('overview-map') && typeof maplibregl!=='undefined'){

const map=new maplibregl.Map({container:'overview-map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'context',type:'raster',source:'osm'}]},center:{{ $state ? '[80.9,27.1]' : '[80.5,22.5]' }},zoom:{{ $state ? '5.1' : '3.2' }},scrollZoom:false});map.addControl(new maplibregl.NavigationControl());map.on('error',()=>{document.getElementById('map-note').textContent='Map tiles are unavailable. Use the place search and state links to explore available pages.'});

}else if(document.getElementById('map-note')){document.getElementById('map-note').textContent='Map unavailable. Use the place search below.'}

</script><script src="/js/sortable-tables.js?v={{ substr(hash_file('sha256', public_path('js/sortable-tables.js')),0,12) }}" defer></script></body></html>
