<!doctype html>

<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/vendor/maplibre/maplibre-gl.css">

@include('seo-metadata', ['canonical' => $state ? route('states.show', ['state' => $state]) : route('home'), 'seoTitle' => $title.' · Elections & places · Pollmedia', 'seoDescription' => 'Explore available election results, constituency pages and district data, with official sources and clear coverage dates.', 'breadcrumbs' => $state ? ['India' => route('home'), 'Uttar Pradesh' => route('states.show', ['state' => $state])] : ['India' => route('home')]])

<style>

*{box-sizing:border-box}body{margin:0;background:#f5f6f0;color:#173d37;font:15px/1.6 system-ui,sans-serif}a{color:#176c55;text-underline-offset:4px}header{background:#123d35;padding:20px 5vw;display:flex;justify-content:space-between}header a{color:#def1e4;text-decoration:none}.brand{font-size:27px;font-weight:750}header nav{display:flex;gap:24px;align-items:center}main{max-width:1220px;margin:auto;padding:40px 24px}h1{font-size:64px;line-height:1.1;letter-spacing:-2px;margin:16px 0}h2{font-size:27px;margin:6px 0 18px}h3{margin:8px 0}p{color:#65766c}.kicker{font-size:11px;text-transform:uppercase;letter-spacing:1.6px;font-weight:700}.hero{display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:center}.map{height:330px;border-radius:14px;overflow:hidden;border:1px solid #dce5dc}.small{font-size:12px}.notice{background:#fff8e8;border-left:3px solid #c9ab69;padding:12px 18px;margin:24px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:white;border:1px solid #dce5dc;border-radius:10px;padding:22px;min-width:0}section{margin:36px 0;scroll-margin-top:20px}.search{display:flex;flex-wrap:wrap;align-items:end;gap:14px;margin:20px 0}label{display:block;font-size:12px;margin-bottom:5px}input,select,button{font:inherit;padding:11px 14px;border:1px solid #b8cabd;border-radius:6px}input{width:min(350px,75vw)}button,.button{background:#176c55;color:white;border:0;cursor:pointer}.button{display:inline-block;text-decoration:none;padding:10px 16px;border-radius:6px}.tag{font-size:11px;background:#e4ede1;padding:4px 9px;border-radius:4px}footer{border-top:1px solid #dce5dc;padding-top:20px;font-size:12px;color:#65766c}@media(max-width:760px){.hero,.grid{grid-template-columns:1fr}h1{font-size:48px}header nav{gap:12px;font-size:12px}.map{height:270px}}



.home{background:radial-gradient(ellipse at 12% 10%,#e4efdf 0,transparent 36%),#f6f7f1}.home main{padding-top:52px}.home .hero{gap:48px}.home .hero h1{font-size:clamp(44px,5.7vw,72px);letter-spacing:-3px;line-height:1.04;margin:22px 0}.home .hero h1 em{font-style:normal;color:#258368}.intro{font-size:18px;line-height:1.7;max-width:570px}.hero-actions{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:24px 0}.home .button{padding:13px 22px;border-radius:8px;box-shadow:0 5px 14px #176c5518}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:7px 12px;background:#e2eddf;border:1px solid #ccddc8;border-radius:30px;font-size:11px;letter-spacing:1px;text-transform:uppercase}.eyebrow:before{content:'';width:7px;height:7px;background:#258368;border-radius:50%}.map-shell{background:white;border:1px solid #dce5dc;border-radius:20px;padding:14px;box-shadow:0 18px 50px #173d3710;transform:rotate(1deg)}.map-shell .map{height:320px;border-radius:12px}.map-caption{padding:0 9px}.map-caption strong{display:block;font-size:14px;margin-top:10px}.map-caption p{margin:5px 0}.value-strip{display:flex;flex-wrap:wrap;gap:12px 24px;margin-top:24px;font-size:12px;color:#4d6e62}.value-strip span:before{content:'✓';color:#258368;font-weight:800;margin-right:7px}.purpose{margin-top:50px}.section-top{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:22px}.section-top h2{margin-bottom:0}.section-top p{max-width:420px;margin:0}.feature{position:relative;padding:28px;border-top:3px solid #258368;transition:transform .18s,box-shadow .18s}.feature:hover{transform:translateY(-3px);box-shadow:0 10px 28px #173d3710}.feature-number{display:flex;width:38px;height:38px;background:#e4ede1;align-items:center;justify-content:center;border-radius:10px;font-size:13px;font-weight:750;margin-bottom:22px}.feature h3{font-size:21px;letter-spacing:-.5px}.feature p{min-height:78px}.feature a{font-weight:650;font-size:13px}.home .notice{border-radius:0 9px 9px 0;font-size:13px}.home #politics .search{background:#e9efe4;border-radius:12px;padding:22px}.home .card{border-radius:12px}.about-note{background:#173d37;border-radius:14px;padding:25px 30px;display:flex;gap:30px;align-items:center;margin:24px 0}.about-note h3{color:#eff6e9;min-width:210px;font-size:19px}.about-note p{color:#c5d9cb;margin:0;font-size:14px}.home a:focus-visible,.home button:focus-visible,.home input:focus-visible,.home select:focus-visible{outline:3px solid #d5a448;outline-offset:4px}@media(max-width:760px){.home main{padding-top:30px}.home .hero{gap:25px}.home .hero h1{letter-spacing:-2px}.map-shell{transform:none}.section-top,.about-note{display:block}.section-top p{margin-top:12px}.about-note h3{margin-top:0}.feature p{min-height:0}.intro{font-size:16px}.home #politics .search{padding:15px}.search select{max-width:100%}.search>div{max-width:100%}}@media(prefers-reduced-motion:reduce){.feature{transition:none}.feature:hover{transform:none}}

</style></head><body class="{{ $state ? 'state' : 'home' }}"><header><a class="brand" href="{{ route('home') }}">pollmedia.</a><nav><a href="{{ route('geography.india') }}">Explore India</a><a href="{{ route('geography.index') }}">Global explorer</a><a href="#politics">Elections & places</a><a href="#administration">Administration</a><a href="/india/sir">SIR</a><a href="{{ route('sources.index') }}">Data status</a></nav></header><main>

@if($state)

<div class="hero"><div><div class="kicker"><a href="{{ route('india') }}">India</a> @if($state) / Uttar Pradesh @endif · Public information</div><h1>{{ $title }},<br>place by place.</h1><p>Explore elections, representatives and the places they serve. Follow the official sources behind every available result.</p><a class="button" href="#politics">Find your place ↓</a></div><div><div class="map" id="overview-map" role="region" aria-label="{{ $title }} geographic context map"></div><p class="small" id="map-note">Geographic context only; constituency boundaries and data overlays are not yet available.</p></div></div>

@else

<div class="hero"><div><span class="eyebrow">Your place. Your representatives. Your information.</span><h1>India,<br>place by place.<br><em>Understand yours.</em></h1><p class="intro">Pollmedia brings election results, public representatives and local development information together—so you can understand who represents you and what the data says about your area.</p><div class="hero-actions"><a class="button" href="#politics">Explore your place <span aria-hidden="true">→</span></a><a href="#about">How Pollmedia helps ↓</a></div><div class="value-strip"><span>Official source links</span><span>Dated information</span><span>Clear coverage</span></div></div><div class="map-shell"><div class="map" id="overview-map" role="region" aria-label="India geographic context map"></div><div class="map-caption"><strong>A national vision. Starting locally.</strong><p class="small">Explore our first connected pages in Uttar Pradesh.</p><p class="small" id="map-note">Geographic context only; constituency boundaries and data overlays are not yet available.</p></div></div></div>

<section id="about" class="purpose"><div class="section-top"><div><div class="kicker">What is Pollmedia?</div><h2>A clearer picture of public life.</h2></div><p>Start with a place. Explore its elections, find its representatives and follow the evidence.</p></div><div class="grid"><article class="card feature"><span class="feature-number" aria-hidden="true">01</span><h3>Understand the vote</h3><p>Explore available election results: who won, their party, vote shares and the margin of victory.</p><a href="{{ route('places.show',['type'=>'pc','slug'=>'pilibhit']) }}#elections">Explore election results →</a></article><article class="card feature"><span class="feature-number" aria-hidden="true">02</span><h3>Know who represents you</h3><p>Find MPs, MLAs and district authorities in the available directories, with official links and verification dates.</p><a href="{{ route('places.show',['type'=>'district','slug'=>'pilibhit']) }}#people">Meet the representatives →</a></article><article class="card feature"><span class="feature-number" aria-hidden="true">03</span><h3>Get to know your area</h3><p>Connect constituencies and districts. Explore available Census measurements, village maps and local data.</p><a href="{{ route('places.show',['type'=>'district','slug'=>'pilibhit']) }}#development">Explore local information →</a></article></div><div class="about-note"><h3>See the information.<br>Check the source.</h3><p>Pollmedia is a research platform, not an official government portal. Official links sit alongside the data, and missing coverage is labelled so you can see what is available and what is still to come.</p></div></section>

@endif

<p class="notice"><strong>Local research pilot.</strong> Available coverage: {{ $coverage->get('ac',0) }} Uttar Pradesh Assembly constituencies, {{ $coverage->get('pc',0) }} parliamentary constituency pages and {{ $coverage->get('district',0) }} district pages. Election years and administrative coverage vary by place. These are not nationwide totals.</p>

<section id="states"><div class="kicker">Start with a state</div><h2>Explore available coverage</h2><div class="grid"><article class="card"><span class="tag">Pilot coverage</span><h3><a href="{{ route('states.show', ['state'=>'uttar-pradesh']) }}">Uttar Pradesh →</a></h3><p>{{ $coverage->get('pc',0) }} PC · {{ $coverage->get('ac',0) }} AC pages · {{ $coverage->get('district',0) }} linked district pages</p><p class="small">Current place profiles are limited to Uttar Pradesh; the historical Lok Sabha archive covers other states too.</p></article><article class="card"><h3>Election results</h3><p>Browse historical Lok Sabha editions across India, or open a constituency for its linked results.</p><p><a href="{{ route('elections.history') }}">Explore the Lok Sabha archive →</a></p><a href="https://www.eci.gov.in/">Election Commission of India ↗</a></article><article class="card"><h3>Reports & updates</h3><p>Generate a Pilibhit district draft from accepted election, Census and village-mapping evidence. Quarterly and annual editions are available for review.</p><a href="{{ route('reports.pilibhit') }}">Open district report draft →</a></article></div></section>

<section id="politics"><div class="kicker">01 / Politics & elections</div><h2>Find a constituency or district</h2><form class="search" method="get" action="{{ $state ? route('states.show',['state'=>$state]) : route('home') }}#politics"><div><label for="place-select">Choose an available place</label><select id="place-select" name="place"><option value="">All available places</option>@foreach($options as $option)<option value="{{ $option->slug }}" @selected($selected===$option->slug)>{{ $option->name }} {{ strtoupper($option->type) }}</option>@endforeach</select></div><div><label for="place-query">Place name</label><input id="place-query" type="search" name="q" value="{{ $query }}" placeholder="Try Pilibhit, Puranpur or Baheri"></div><div><label for="place-type">Page type</label><select id="place-type" name="type"><option value="">All pages</option><option value="pc" @selected($type==='pc')>Parliamentary constituency (PC)</option><option value="ac" @selected($type==='ac')>Assembly constituency (AC)</option><option value="district" @selected($type==='district')>District</option></select></div><button type="submit">Search</button><a href="{{ $state ? route('states.show',['state'=>$state]) : route('home') }}#politics">Clear</a></form><p class="small" role="status">{{ $places->total() }} available pages match your search.</p><div class="grid">@forelse($places as $place)<article class="card"><span class="tag">{{ ['pc'=>'Parliamentary constituency','ac'=>'Assembly constituency','district'=>'District'][$place->type] }}</span><h3><a href="{{ route('places.show',['type'=>$place->type,'slug'=>substr($place->slug,strlen($place->type)+1)]) }}">{{ $place->name }} {{ strtoupper($place->type) }} →</a></h3><p class="small">Uttar Pradesh · @if($years->has($place->id))Results: {{ $years[$place->id]->pluck('year')->unique()->sort()->implode(', ') }}

@elseif($place->type==='district')

Linked constituencies and available administrative data

@else

Election results not imported

@endif

</p></article>@empty<div class="card">No imported pages match. Try another place name or clear the filters.</div>@endforelse</div>{{ $places->links() }}</section>

<section id="administration"><div class="kicker">02 / Administration & development</div><h2>Understand the local area</h2><div class="grid"><article class="card"><h3>Districts & authorities</h3><p>Find available official directories and dated development measurements on district pages.</p><a href="{{ route('home',['type'=>'district']) }}#politics">Explore district pages →</a></article><article class="card"><h3>Villages & urban wards</h3><p>Explore 1,435 village profiles from the Pilibhit 2011 Census workbook, with population, households and official sources. Urban ward pages and electoral links remain pending.</p><a href="{{ route('villages.index') }}">Explore village profiles →</a></article><article class="card"><h3>Polling stations & parts</h3><p>Dedicated pages and AC relationships are pending official mapping. The SIR explorer contains a limited Pilibhit AC sample.</p><a href="/india/sir">Open SIR explorer →</a></article></div></section>

<footer><a href="{{ route('sitemap') }}">Sitemap</a> · Pollmedia · Local research pilot · Coverage and source dates are shown on individual pages.</footer></main>

<script src="/vendor/maplibre/maplibre-gl.js"></script><script>

if(typeof maplibregl!=='undefined'){

const map=new maplibregl.Map({container:'overview-map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'context',type:'raster',source:'osm'}]},center:{{ $state ? '[80.9,27.1]' : '[80.5,22.5]' }},zoom:{{ $state ? '5.1' : '3.2' }},scrollZoom:false});map.addControl(new maplibregl.NavigationControl());map.on('error',()=>{document.getElementById('map-note').textContent='Map tiles are unavailable. Use the place search and state links to explore available pages.'});

}else{document.getElementById('map-note').textContent='Map unavailable. Use the place search below.'}

</script></body></html>
