<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <title>Pilibhit AC 127 · Village evidence pilot | Pollmedia</title>
    <link rel="stylesheet" href="{{ asset('css/pilibhit-ac-pilot.css') }}">
    <script type="module" src="{{ asset('js/pilibhit-ac-pilot.js') }}"></script>
</head>
<body>
<header><a class="brand" href="https://pollmedia.org">Pollmedia<span>Places, people & public evidence</span></a><a href="{{ $data['links']['constituency'] }}">Pilibhit election history ↗</a></header>
<main id="ac-pilot" data-source="{{ asset('maps/pilibhit-ac-pilot.json') }}">
    <div class="breadcrumb">Uttar Pradesh / Pilibhit / Assembly constituency 127</div>
    <section class="hero"><div><p class="eyebrow">Village evidence · Pilot</p><h1>Know the places<br>within Pilibhit.</h1><p>Explore Census villages linked to AC 127, compare their boundaries, and follow the official evidence behind each connection.</p></div><aside><strong>Three sources, one place</strong><p>Census 2011 counts<br>LGD links checked 16 September 2026<br>Polling areas published 26 December 2025</p><span class="pill">Rural coverage · Urban wards excluded</span></aside></section>
    <nav class="section-nav" aria-label="Dashboard sections"><a href="{{ route('pilibhit-district-pilot') }}">District dashboard ↗</a><a href="#places">Map & villages</a><a href="#baseline">Census baseline</a><a href="#polling">Polling evidence</a><a href="#review-queue">Review queue</a><a href="#sources">Sources & method</a></nav>
    <section class="metrics" aria-label="Coverage summary">
        <article><span>Directory-linked villages</span><strong>{{ $data['summary']['linked_village_baseline']['villages'] }}</strong><small>Unique Census 2011 codes</small></article>
        <article><span>Map agrees at ≥99.5% overlap</span><strong>{{ $data['summary']['statuses']['linked_inside'] ?? 0 }}</strong><small>Geographic corroboration</small></article>
        <article><span>Linked villages needing map review</span><strong>{{ $data['summary']['statuses']['linked_review'] ?? 0 }}</strong><small>Edges, outside or missing geometry</small></article>
        <article><span>Additional map candidates</span><strong>{{ $data['summary']['statuses']['map_candidate'] ?? 0 }}</strong><small>No accepted AC directory link here</small></article>
    </section>
    <p class="notice">These sources describe different dates. An overlap discrepancy is a review flag, not proof that either boundary is wrong. This pilot does not certify the AC boundary or an official constituency population.</p>
    <section id="places" class="panel">
        <div class="section-heading"><div><p class="eyebrow">Explore the connections</p><h2>Map & village directory</h2></div><a id="download" href="{{ route('pilibhit-ac-pilot', array_merge($filters, ['format'=>'csv'])) }}">Download filtered CSV ↓</a></div>
        <form id="filters" method="get" class="filters">
            <label>Village name or code<input type="search" name="q" id="q" maxlength="120" value="{{ $filters['q'] }}" placeholder="Try Phulaiya or 131192"></label>
            <label>Evidence status<select name="status" id="status"><option value="all">All places</option>@foreach($statusLabels as $key=>$label)<option value="{{ $key }}" @selected($filters['status']===$key)>{{ $label }}</option>@endforeach</select></label>
            <label>Review cause<select name="reason" id="reason">@foreach(['all'=>'All causes','polling_directory_conflict'=>'Polling table vs LGD','directory_map_disagreement'=>'Directory vs map','missing_directory_link'=>'Missing AC directory link','corroborated_directory_map'=>'Directory + map agree'] as $key=>$label)<option value="{{ $key }}" @selected($filters['reason']===$key)>{{ $label }}</option>@endforeach</select></label>
            <button type="submit">Show places</button><button type="button" id="reset">Reset</button>
        </form>
        <div class="map-grid"><div class="map-wrap"><div class="map-controls"><button type="button" id="zoom-in" aria-label="Zoom in">+</button><button type="button" id="zoom-out" aria-label="Zoom out">−</button><button type="button" id="fit-map">Fit map</button></div><svg id="village-map" viewBox="0 0 760 540" role="group" aria-label="Pilibhit constituency and Census village polygons"></svg><p id="map-message" role="status">Loading interactive map… The directory below is available without JavaScript.</p><div class="legend"><span class="inside">Linked + map agrees</span><span class="review">Linked + map review</span><span class="candidate">Map candidate</span><span class="outline">AC outline</span></div></div>
        <aside id="place-detail" aria-live="polite"><p class="eyebrow">Select a village</p><h3>Evidence for each place</h3><p>Choose a shape or a village name to see its Census counts, directory links, map overlap and reviewed polling references.</p><p class="muted">Village figures describe Census 2011. Land overlap never allocates population.</p></aside></div>
        <p id="result-count" role="status">{{ $rows->total() }} matching places · showing {{ $rows->count() }}</p>
        <div class="table-wrap"><table><caption class="sr-only">Census villages and constituency evidence</caption><thead><tr><th>Village / Census code</th><th>Evidence status</th><th>2011 population</th><th>Literacy 7+</th><th>Land inside AC</th></tr></thead><tbody id="village-rows">@foreach($rows as $row)<tr><td><button type="button" class="village-link" data-code="{{ $row['code'] }}">{{ $row['name'] }}</button><small>{{ $row['code'] }}</small></td><td>{{ $statusLabels[$row['status']] }}</td><td>{{ number_format($row['census']['population']) }}</td><td>{{ $row['census']['population']>$row['census']['population_0_6'] ? number_format(100*$row['census']['literate']/($row['census']['population']-$row['census']['population_0_6']),1).'%' : 'Unavailable' }}</td><td>{{ $row['land_overlap_percent']===null ? 'Unavailable' : number_format($row['land_overlap_percent'],2).'%' }}</td></tr>@endforeach</tbody></table></div>
        <div id="pagination">{{ $rows->links() }}</div><noscript><p>Enable JavaScript to explore the map and village evidence panels. Search and CSV export still work.</p></noscript>
    </section>
    <section id="baseline" class="panel"><p class="eyebrow">A dated demographic reference</p><h2>Census 2011 rural village baseline</h2><p>Sum of the {{ $data['summary']['linked_village_baseline']['villages'] }} unique Census villages linked through the imported LGD report. Includes map-review cases. This is not the whole AC population, a current population estimate, or a boundary-adjusted total.</p><div class="metrics baseline">@php $baseline=$data['summary']['linked_village_baseline']; @endphp<article><span>Population in linked villages</span><strong>{{ number_format($baseline['population']) }}</strong></article><article><span>Households</span><strong>{{ number_format($baseline['households']) }}</strong></article><article><span>Literacy · age 7+</span><strong>{{ number_format($baseline['literacy_rate'],2) }}%</strong></article><article><span>Population aged 7+</span><strong>{{ number_format($baseline['population_7_plus']) }}</strong></article></div><p class="muted">Literacy = sum of literates ÷ sum of population aged 7+. Village percentages are not averaged. Filtering the map does not change this baseline.</p></section>
    <section id="polling" class="panel"><div class="section-heading"><div><p class="eyebrow">Booths connect places to elections</p><h2>Polling evidence</h2></div><a href="{{ $data['links']['final_stations'] }}" target="_blank" rel="noopener">Approved coverage table ↗</a></div><p>{{ count($data['stations']) }} booth names captured from the official SIR discrepancy-list index; {{ $data['summary']['reviewed_booths'] }} booth coverage rows visually reviewed on PDF page 2. Building names alone do not establish the served territory.</p>
    @if($data['vision'] ?? null)<p class="notice">Vision extracted {{ $data['summary']['vision_booths'] }} booth rows from {{ count($data['vision']['pages']) }} approved-table pages using {{ $data['vision']['provider'] }}. The source Hindi and suggested Census names appear together below. Model name matches remain suggestions; they do not change village membership, census totals or boundary coordinates.</p>@endif
    <label>Find a booth or served area<input id="booth-search" type="search" placeholder="Booth number, Hindi area or Census name"></label><div id="booth-list" class="booth-list">@foreach(collect($data['stations'])->where('coverage_review','!=','not_reviewed') as $station)<article><strong>Booth {{ $station['number'] }} · {{ $station['name'] }}</strong><p>Reviewed named areas: {{ implode(', ', $station['coverage_names']) }}</p>@if(count($station['unresolved_names']??[]))<p>Ambiguous Census identity: {{ implode(', ', $station['unresolved_names']) }}</p>@endif<a href="{{ $data['links']['final_stations'] }}#page={{ $station['source_pdf_page'] }}" target="_blank" rel="noopener">Coverage source · page {{ $station['source_pdf_page'] }} ↗</a></article>@endforeach</div><p class="muted">Several booths may serve one village; one booth may serve several localities. A partial booth catchment does not by itself mean the village is split between constituencies.</p></section>
    <section id="review-queue" class="panel"><p class="eyebrow">Review the cause, not every polygon</p><h2>Grouped review queue</h2><p>Start with official source conflicts, then missing directory links and geographic discrepancies. These groups explain why a place needs attention; no boundary correction is inferred from a name match.</p><div class="source-grid">@foreach(['polling_directory_conflict'=>'Polling table vs LGD assignment','directory_map_disagreement'=>'Directory vs map overlap','missing_directory_link'=>'Map candidate without AC link'] as $reason=>$label)<article><h3>{{ $label }}</h3><strong>{{ $data['summary']['review_reasons'][$reason] ?? 0 }} places</strong><ul>@foreach(collect($data['rows'])->where('review_reason',$reason)->take(5) as $row)<li><a href="#village-{{ $row['code'] }}" class="review-village" data-code="{{ $row['code'] }}">{{ $row['name'] }} · {{ $row['code'] }}</a></li>@endforeach</ul></article>@endforeach</div>@if($data['vision'] ?? null)<p>Vision name suggestions: {{ $data['vision']['summary']['unique_name_suggestion'] ?? 0 }} unique normalized matches; {{ $data['vision']['summary']['probable_name_suggestion'] ?? 0 }} probable spelling matches; {{ $data['vision']['summary']['ambiguous_name'] ?? 0 }} ambiguous entries; {{ $data['vision']['summary']['locality_or_unreadable'] ?? 0 }} locality or unreadable entries. Counts refer to repeated polling-area mentions, not unique villages.</p>@endif</section>
    <section id="sources" class="panel"><p class="eyebrow">Inspect the evidence</p><h2>Sources, gaps & method</h2><div class="source-grid"><article><h3>Census counts</h3><p>2011 village population, households, literates and children aged 0–6.</p><a href="{{ $data['links']['census'] }}" target="_blank" rel="noopener">Official Census publication ↗</a></article><article><h3>Directory assignment</h3><p>LGD village → AC/PC report and explicit LGD → Census code links, checked {{ $data['scope']['electoral_checked_on'] }}.</p><a href="{{ $data['links']['electoral'] }}" target="_blank" rel="noopener">LGD electoral report ↗</a></article><article><h3>Map sources</h3><p>Community AC outline with unverified reference year; Survey of India village geometry with unverified edition correspondence. Differences remain visible.</p><a href="{{ $data['links']['village_boundaries'] }}" target="_blank" rel="noopener">Survey of India village boundaries ↗</a></article><article><h3>Polling records</h3><p>SIR booth index plus a bounded visual review of approved named polling areas.</p><a href="{{ $data['links']['stations'] }}" target="_blank" rel="noopener">Official SIR booth index ↗</a></article></div>
    <details><summary>How map checks work</summary><p>Polygons are compared in a local metre-based projection (UTM zone 44N). At least 99.5% village land overlap is labelled “map agrees”; 0.5–99.5% is an edge overlap. The tolerance accommodates small source differences and does not certify legal membership. Invalid or ambiguous geometries remain unresolved. Population is never multiplied by land overlap.</p><p>Urban wards, historical reconstruction, complete polling catchments and individual voter records are outside this pilot.</p><a href="{{ asset('maps/pilibhit-ac-pilot.json') }}">Download evidence package with source checksums ↓</a></details>
    @if(count($data['gaps']))<details><summary>{{ count($data['gaps']) }} directory record needs a Census link</summary>@foreach($data['gaps'] as $gap)<p>{{ $gap['name'] }} · LGD {{ $gap['lgd_code'] }} — {{ $gap['reason'] }}</p>@endforeach</details>@endif
    </section>
</main><footer>Pollmedia · AC 127 pilot · Source dates remain attached to their evidence.</footer>
</body></html>
