<section id="sources"><div class="kicker">Evidence behind this page</div><h2>Sources & references</h2><div class="grid2">
@if($selectedElection)
<article class="card"><h3>Election results · {{ $selectedElection->year }}</h3><p><a href="{{ $selectedElection->url }}" target="_blank" rel="noreferrer">Official ECI statistical report ↗</a></p><p class="small">{{ $selectedElection->source_locator }} · Checked {{ substr($selectedElection->retrieved_at,0,10) }}. Party labels refer to the election year.</p>@if($selectedElection->totals_url)<a href="{{ $selectedElection->totals_url }}" target="_blank" rel="noreferrer">Official totals report ↗</a>@endif</article>
@endif
<article class="card"><h3>Representatives & authorities</h3>@forelse($people->unique(fn ($person) => $person->url.'|'.$person->verified_at) as $person)<p><a href="{{ $person->url }}" target="_blank" rel="noreferrer">Official public-office directory ↗</a><br><span class="small">Last checked {{ substr($person->verified_at,0,10) }}. These are dated directory checks, not appointment dates.</span></p>@empty<p>No verified officeholder source has been imported for this scope.</p>@endforelse</article>
@if($villageCoverage['url'])<article class="card"><h3>Village electoral connections</h3><p><a href="{{ $villageCoverage['url'] }}" target="_blank" rel="noreferrer">LGD PC/AC mapping report ↗</a></p><p class="small">Checked {{ $villageCoverage['checked_on'] }}. Coverage counts distinguish mapped villages from imported Census profiles; neither is a constituency population total.</p></article>
@endif
<article class="card"><h3>Connected places</h3>@forelse($relations->unique('source_url') as $related)<p><a href="{{ $related->source_url }}" target="_blank" rel="noreferrer">Official geographical relationship source ↗</a><br><span class="small">Checked {{ $related->checked_on }}.</span></p>@empty<p>No geographical relationship source has been imported.</p>@endforelse</article>
@if($observations->isNotEmpty())
<article class="card"><h3>Historical measurements</h3>@foreach($observations->unique(fn ($item) => $item->url.'|'.$item->period) as $observation)<p><a href="{{ $observation->url }}" target="_blank" rel="noreferrer">Official measurement source · {{ $observation->period }} ↗</a></p>@endforeach<p class="small">Reference years describe the measurements, not today's population.</p></article>
@endif
</div><p class="small">Sources beside individual tables and records point to the same evidence. Refreshes are currently manual.</p><a href="{{ route('sources.index') }}">All sources & update status →</a></section>
