@extends('geography-layout')
@section('title', 'Polling-station results and official Form 20 sources')
@section('content')
<h1>Polling-station results</h1>
<p>Official Form 20 sources and extracted tables. <a href="{{ route('elections.assembly') }}">AC general elections</a> · <a href="{{ route('elections.history') }}">PC general elections</a> · <a href="{{ route('elections.by-election-results') }}">By-elections</a>.</p>
<p class="notice">{{ $index['scope_note'] ?? 'The source collection has not yet been installed.' }}</p>
<p class="notice">† Available source records are published with warnings while discrepancies are reviewed. Scanned or unreadable values remain identified as such, and the preserved original stays available for checking.</p>
<p>{{ $all->count() }} preserved source documents; {{ number_format($all->sum('polling_rows')) }} extracted polling-station rows across source editions.</p>
<form method="get" class="card filters"><div><label for="state">State / territory source directory</label><select id="state" name="state"><option value="">All directory entries</option>@foreach($states as $state)<option value="{{ $state['state'] }}" @selected(($input['state'] ?? '') === $state['state'])>{{ $state['state'] }}</option>@endforeach</select></div><button>Choose state</button></form>
<form method="get" class="card filters">@if(isset($input['state']))<input type="hidden" name="state" value="{{ $input['state'] }}">@endif<div><label for="source">Official source document</label><select id="source" name="source">@foreach($choices as $choice)<option value="{{ $choice['id'] }}" @selected(($source['id'] ?? '') === $choice['id'])>{{ $choice['state'] }} · {{ $choice['name'] }} · {{ $choice['polling_rows'] }} extracted rows</option>@endforeach</select></div><button @disabled($choices->isEmpty())>Open document</button></form>
@if($source)
<section class="card"><h2>{{ $source['name'] }}</h2><p>Found through the {{ $source['state'] }} source directory · <a href="{{ $source['source_url'] }}" target="_blank" rel="noopener noreferrer">Official original document</a> · <a href="{{ $source['discovered_on'] }}" target="_blank" rel="noopener noreferrer">Official source page</a></p><p>Official websites may link to other jurisdictions. Use the document heading to identify the election and constituency.</p>
@if($source['has_preserved_original'] ?? false)<p><a href="{{ route('elections.polling-stations', ['source' => $source['id'], 'download' => 1]) }}">Download preserved original</a></p>@endif
@if($source['pages'])<form method="get" class="filters"><input type="hidden" name="source" value="{{ $source['id'] }}"><div><label for="page">Page / worksheet</label><select id="page" name="page">@foreach($source['pages'] as $option)<option value="{{ $option['page'] }}" @selected($page === $option['page'])>{{ $option['sheet'] ?? ('Page '.$option['page']) }} · {{ $option['polling_rows'] }} polling rows</option>@endforeach</select></div><button>Open table</button></form>@endif
@if($data)
@foreach($data['notes'] as $note)<p class="notice">† {{ $note }}</p>@endforeach
@foreach($data['polling_rows'] as $row)<details class="row"><summary>Polling station {{ $row['polling_station'] }} · Valid votes: {{ $row['valid_votes'] === null ? 'Not read' : number_format($row['valid_votes']) }} @if($row['notes'])†@endif</summary><table><thead><tr><th>Candidate as reported</th><th>Votes</th></tr></thead><tbody>@foreach($row['candidate_votes'] as $candidate)<tr><td>{{ $candidate['name'] }}</td><td>{{ $candidate['votes'] === null ? 'Not read †' : number_format($candidate['votes']) }}</td></tr>@endforeach</tbody></table><p>NOTA: {{ $row['nota'] ?? 'Not read' }} · Rejected: {{ $row['rejected_votes'] ?? 'Not read' }} · Total: {{ $row['total_votes'] ?? 'Not read' }}</p>@foreach($row['notes'] as $note)<p>† {{ $note }}</p>@endforeach</details>@endforeach
<h3>Original source tables <sup>†</sup></h3><p>Includes headings, postal ballots and totals where extracted. These rows are retained separately from identified polling-station rows.</p>
@foreach($data['tables'] as $table)<details class="card"><summary>Source table {{ $table['number'] }}</summary><div class="scroll"><table><tbody>@foreach($table['cells'] as $cells)<tr>@foreach($cells as $cell)<td>{{ $cell === null || $cell === '' ? '—' : $cell }}</td>@endforeach</tr>@endforeach</tbody></table></div></details>@endforeach
@if(!empty($data['text']))<details class="card"><summary>Extracted page text †</summary><p>Reading order and characters may differ from the PDF. This text is retained for checking the extracted tables.</p><pre style="white-space: pre-wrap; overflow-wrap: anywhere">{{ $data['text'] }}</pre></details>@endif
@if($ocr)<details class="card"><summary>Text read from the scanned page †</summary>@foreach($ocr['notes'] as $note)<p class="notice">† {{ $note }}</p>@endforeach<pre style="white-space: pre-wrap; overflow-wrap: anywhere">{{ $ocr['text'] }}</pre></details>@endif
<p class="notice">† Extracted text and table boundaries require review against the official original. Missing cells remain —, not zero. Historical polling-station numbers are scoped to this source document and are not mapped automatically to current stations.</p>
@else<p class="notice">The original file is preserved. Table extraction is still pending.</p>@endif
</section>
@else<p class="notice">No preserved documents are available for this selection yet. This is a collection gap, not evidence that no polling-station data exists.</p>@endif
<details class="card"><summary>State directory coverage and pending discovery</summary><p>Directory labels are retained from official sources, including older territorial entries.</p><table><thead><tr><th>Directory entry</th><th>Documents</th><th>Queued pages</th><th>Access / download issues</th></tr></thead><tbody>@foreach($states as $state)<tr><td><a href="{{ $state['url'] }}" target="_blank" rel="noopener noreferrer">{{ $state['state'] }}</a></td><td>{{ $state['documents'] }}</td><td>{{ $state['pending_pages'] }}</td><td>{{ count($state['errors']) + ($state['failed_documents'] ?? 0) }}</td></tr>@endforeach</tbody></table></details>
@endsection
