<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>Search places & election results · Pollmedia</title><link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256', public_path('css/election-dashboard.css')),0,12) }}"><script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script>@include('site-theme')</head><body class="election-ui">@include('public-header')<div class="dashboard-shell page-without-sidebar"><main class="dashboard-main"><h1>{{ \App\Services\PublicLanguage::text('Find a place. Explore its story.') }}</h1><p>{{ \App\Services\PublicLanguage::text('Search Lok Sabha, Assembly (AC), districts and available village pages. Open a place to compare its election history.') }}</p><form class="filters panel" action="{{ route('public.search') }}"><div><label for="query">{{ \App\Services\PublicLanguage::text('Place, village code or SIR reference') }}</label><input id="query" name="q" value="{{ $q }}" minlength="2" maxlength="100" required></div><div><label for="kind">{{ \App\Services\PublicLanguage::text('Place type') }}</label><select id="kind" name="kind"><option value="">{{ \App\Services\PublicLanguage::text('All types') }}</option>@foreach(['pc'=>'Lok Sabha','ac'=>'Assembly (AC)','district'=>'District','village'=>'Village','sir'=>'SIR references'] as $value=>$label)<option value="{{ $value }}" @selected($kind===$value)>{{ \App\Services\PublicLanguage::text($label) }}</option>@endforeach</select></div><div><label for="sir-year">SIR revision year</label><select id="sir-year" name="year"><option value="">All indexed years</option>@foreach($sirYears as $sirYear)<option value="{{ $sirYear }}" @selected($year === (int) $sirYear)>{{ $sirYear }}</option>@endforeach</select></div><button>{{ \App\Services\PublicLanguage::text('Search') }}</button></form>
@if(mb_strlen($q)<2)<p>{{ \App\Services\PublicLanguage::text('Enter at least two characters to find available pages.') }}</p>@else
@if($kind !== 'sir')<section class="panel"><h2>Places</h2>
<div class="place-list ranked-results">@forelse($suggestions as $match)<a href="{{ $match['url'] }}"><strong>{{ $match['label'] }}</strong><span>{{ $match['type'] }}@if($match['period']) · {{ $match['period'] }}@endif</span></a>@empty<h2>{{ \App\Services\PublicLanguage::text('No matching pages yet') }}</h2><p>{{ \App\Services\PublicLanguage::text('Try another spelling or choose all types. Available records do not cover every place.') }}</p>@endforelse</div>@if($results){{ $results->links() }}@endif</section>@endif
@if(in_array($kind, ['', 'sir']))
<section class="panel"><h2>SIR document references</h2><p>Search by place, polling station, part number, document terms or indexed revision year. Coverage is partial. Individual voter names are not indexed. A missing result does not establish absence from an electoral roll.</p>
@forelse($sirResults as $reference)
<article class="panel"><h3>{{ $reference['label'] }}</h3><p>{{ $reference['title'] }} &#183; {{ $reference['period'] }} &#183; {{ $reference['ac_name'] }} &#183; AC {{ $reference['ac'] }} &#183; Part {{ $reference['part'] }}</p><p>Revision year: {{ $reference['year'] ?? 'Not verified' }} @if($reference['published']) &#183; Document date: {{ $reference['published'] }} @endif</p><p>PDF pages: @forelse($reference['pages'] as $pdfPage)<a href="{{ $reference['pdf_url'] }}#page={{ $pdfPage }}" target="_blank" rel="noopener noreferrer">{{ $pdfPage }}</a>{{ $loop->last ? '' : ', ' }}@empty Page reference unavailable @endforelse</p><p><a href="{{ $reference['url'] }}" target="_blank" rel="noopener noreferrer">{{ $reference['eci_hosted'] ? 'Open ECI PDF' : 'Open official source PDF' }}</a> &#183; Source: {{ $reference['source_host'] }}</p></article>
@empty<p>No indexed SIR document matches this search and year.</p>@endforelse
{{ $sirResults->links() }}<p><a href="https://voters.eci.gov.in/download-eroll" target="_blank" rel="noopener noreferrer">Open ECI electoral-roll downloads</a> &#183; <a href="https://electoralsearch.eci.gov.in/" target="_blank" rel="noopener noreferrer">Search voter names on ECI</a></p><p>Historical years appear here when verified editions are indexed. ECI downloads may require selecting a state, year and constituency.</p></section>
@endif
@endif
</main></div>@include('public-footer')</body></html>
