@php $site=app(\App\Services\SiteSettings::class)->appearance(); $censusState=request()->route('state'); @endphp
<header class="public-header site-header header-{{ $site['header_template'] }}"><a class="brand" href="{{ route('home') }}">@if($site['logo'])<img src="{{ $site['logo'] }}" alt="{{ $site['name'] }}" width="210" height="53">@else<span class="brand-mark" aria-hidden="true"></span><span class="brand-name">{{ $site['name'] }}</span>@endif</a><div class="header-search-wrap" data-place-search><form class="header-search" action="{{ route('public.search') }}" role="search"><label class="visually-hidden" for="site-search">{{ \App\Services\PublicLanguage::text('Search places and public records') }}</label><input id="site-search" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="search-suggestions" autocomplete="off" name="q" type="search" maxlength="100" minlength="2" value="{{ request()->routeIs('public.search') ? request('q') : '' }}" placeholder="{{ \App\Services\PublicLanguage::text('Search district, village, AC or PC') }}" required><button type="submit">{{ \App\Services\PublicLanguage::text('Search') }}</button></form><div id="search-suggestions" class="search-suggestions" role="listbox" hidden></div><span id="search-suggestion-status" class="visually-hidden" role="status"></span></div><nav id="public-navigation" aria-label="{{ \App\Services\PublicLanguage::text('Main navigation') }}">@php $menuStates=app(\App\Services\ElectionGeographySummary::class)->states(); @endphp
@foreach(['elections'=>'Elections','census'=>'Census'] as $topic=>$label)
<details class="topic-menu"><summary>{{ \App\Services\PublicLanguage::text($label) }} <svg class="menu-chevron" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="m4 6 4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></summary><div class="state-megamenu"><div class="mega-heading"><strong>{{ \App\Services\PublicLanguage::text($label) }} · {{ \App\Services\PublicLanguage::text('States & Union Territories') }}</strong><a href="{{ $topic==='elections'?route('elections.history'):route('civic.index') }}">{{ \App\Services\PublicLanguage::text('Explore India') }} →</a></div>
@if($topic==='elections')<nav class="mega-election-links" aria-label="Election pages"><a href="{{ route('elections.history') }}">Lok Sabha elections →</a><a href="{{ route('elections.assembly') }}">Assembly elections →</a><a href="{{ route('elections.by-election-results') }}">By-elections →</a></nav>@endif
<div class="mega-groups">
@foreach(['State'=>'States','Union Territory'=>'Union Territories'] as $group=>$groupLabel)<section><h2>{{ \App\Services\PublicLanguage::text($groupLabel) }}</h2><div class="mega-state-links">@foreach($menuStates->where('kind',$group) as $item)<a href="{{ $topic==='elections'?route('states.show',['state'=>$item['slug'],'election'=>'pc']):route('civic.index',['state'=>$item['slug']]) }}">{{ \App\Services\PublicLanguage::text($item['name']) }}</a>@endforeach</div></section>@endforeach
</div></div></details>
@endforeach
@foreach($site['links'] as $link)@if(!in_array($link['url'],['/india#states','/india/census/explore','/india/elections/lok-sabha']))<a href="{{ $link['url'] }}">{{ \App\Services\PublicLanguage::text($link['label']) }}</a>@endif @endforeach
</nav><div class="language-switch" aria-label="Language / भाषा"><a href="{{ request()->fullUrlWithQuery(['lang'=>'en']) }}" lang="en" @if(app()->getLocale()==='en') aria-current="true" @endif>English</a><span aria-hidden="true">/</span><a href="{{ request()->fullUrlWithQuery(['lang'=>'hi']) }}" lang="hi" @if(app()->getLocale()==='hi') aria-current="true" @endif>हिन्दी</a></div></header>
