@extends('seo-layout')
@section('content')
<h1>Listing SEO</h1><p>Select the listing type, filter its available data, then generate and publish titles, descriptions and keywords directly.</p>
<form method="get" data-manual-submit class="filters" id="seo-filters">
<label>Listing type<select name="type" id="type" onchange="this.form.querySelectorAll('[name=year],[name=state],[name=q]').forEach(input=>input.value='');this.form.submit()">@foreach(['pc'=>'Parliamentary constituencies / Lok Sabha','ac'=>'Assembly constituencies','census'=>'Census listings','village'=>'Villages','district'=>'Districts','sir'=>'SIR listings'] as $value=>$label)<option value="{{ $value }}" @selected($type===$value)>{{ $label }}</option>@endforeach</select></label>
@if($filters['states']->isNotEmpty())<label>State<select name="state" onchange="this.form.querySelector('[name=year]').value='';this.form.submit()"><option value="">All states</option>@foreach($filters['states'] as $option)<option value="{{ $option }}" @selected($state===$option)>{{ $option }}</option>@endforeach</select></label>@endif
@if($filters['years']->isNotEmpty())<label>{{ in_array($type,['pc','ac'])?'Election year':'Census year' }}<select name="year"><option value="">{{ $type==='village'?'Latest available year':'All available years' }}</option>@foreach($filters['years'] as $option)<option value="{{ $option }}" @selected($year===(string)$option)>{{ $option }}</option>@endforeach</select></label>@endif
<label>Listing name<input name="q" value="{{ $search }}" placeholder="Search listing name"></label>
<label>SEO status<select name="mode">@foreach(['all'=>'All pages','missing'=>'Create missing fields','existing'=>'Update existing SEO'] as $value=>$label)<option value="{{ $value }}" @selected(request('mode','all')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Batch size<select name="size">@foreach(['50','100','200','500','all'] as $size)<option value="{{ $size }}" @selected(request('size','50')===$size)>{{ ucfirst($size) }}</option>@endforeach</select></label><button>Filter listings</button></form>
<section class="card"><h2>{{ number_format($pages->total()) }} matching listings</h2>
<form id="publish-seo" method="post" action="{{ route('seo.publish') }}">@csrf
@foreach(['type'=>$type,'year'=>$year,'state'=>$state,'q'=>$search,'mode'=>request('mode','all'),'size'=>request('size','50')] as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach
<label>Publish selection<select name="bulk"><option value="">Checked listings below</option><option value="{{ request('size','50') }}" selected>{{ ucfirst(request('size','50')) }} matching listings</option></select></label>
<label class="row"><input type="checkbox" id="select-all">Select all displayed listings</label>
@forelse($pages as $page)<div class="row"><label><input type="checkbox" name="paths[]" value="{{ $page['path'] }}">{{ $page['label'] }}</label><a href="{{ $page['path'] }}" target="_blank" rel="noopener">View listing ↗</a> <span class="muted">{{ filled($current[$page['path']]->title??null)?'SEO saved':'SEO missing' }}</span></div>@empty<p>No listings match these filters.</p>@endforelse
<label>Generation method<select name="generation"><option value="template">Automatic titles, descriptions and keywords</option><option value="ai">AI wording (up to 10 checked listings)</option></select></label><label>AI provider<select name="provider"><option value="">Choose provider for AI wording</option>@foreach($aiProviders as $id=>$provider)<option value="{{ $id }}">{{ $provider['label'] }} — {{ $provider['configured']?'Configured':'Setup needed' }}</option>@endforeach</select></label>
<p><button id="publish-button" @disabled($pages->total()===0)>Generate and publish SEO now</button></p><p id="generation-progress" role="status"></p></form>{{ $pages->links() }}</section>
<section class="card"><h2>Published SEO history</h2>@forelse($history as $revision)<details><summary>{{ $revision->created_at }} · {{ $revision->path }}</summary><p>{{ $revision->title }}</p><p>{{ $revision->description }}</p><p>Keywords: {{ $revision->keywords }}</p><form method="post" action="{{ route('seo.restore',$revision->id) }}">@csrf<input type="hidden" name="expected_revision" value="{{ $current[$revision->path]->revision_id }}"><button>Restore previous SEO</button></form></details>@empty<p>No SEO publications yet.</p>@endforelse{{ $history->withQueryString()->links() }}</section>
<script>document.getElementById('select-all').addEventListener('change',function(){document.querySelectorAll('input[name="paths[]"]').forEach(input=>input.checked=this.checked);document.querySelector('[name=bulk]').value='';});document.querySelectorAll('input[name="paths[]"]').forEach(input=>input.addEventListener('change',()=>document.querySelector('[name=bulk]').value=''));document.getElementById('publish-seo').addEventListener('submit',()=>{document.getElementById('publish-button').disabled=true;document.getElementById('generation-progress').textContent='Generating and publishing SEO…';});</script>
@endsection
