@extends('seo-layout')
@section('content')
<h1>Nationwide SIR imports</h1><p>Add official electoral-roll parts from any state and year. Each completed package becomes searchable immediately. Reviewed corrections are preserved on repeat imports.</p>
<p><a href="{{ route('sir.admin.index') }}">Browse voter records</a> · <a href="https://voters.eci.gov.in/download-eroll" target="_blank" rel="noopener">Official ECI roll downloads</a></p>
<form class="card" method="post" enctype="multipart/form-data" action="{{ route('sir.imports.store') }}" data-manual-submit>@csrf<h2>Import a prepared part</h2><p>Upload extracted records together with the unchanged official PDF. Include all entries and the printed totals; unclear details stay flagged for review.</p><div class="field"><label for="records-file">Records JSON (maximum 50 MB)</label><input id="records-file" name="records_file" type="file" accept=".json" required></div><div class="field"><label for="pdf-file">Original official PDF (maximum 100 MB)</label><input id="pdf-file" name="pdf_file" type="file" accept=".pdf" required></div><div class="field"><label for="sha256">Records JSON SHA-256</label><input id="sha256" name="sha256" required pattern="[a-f0-9]{64}"></div><button>Import and publish part</button></form>
<h2>Published coverage</h2><p>These counts describe imported editions. Different years and editions remain separate.</p>@forelse($coverage as $row)<div class="card"><strong>{{ $row->state_name ?: $row->state_code }} · {{ $row->year }}</strong><p>{{ number_format($row->records_count) }} entries · {{ $row->acs_count }} ACs · {{ $row->editions_count }} source PDFs</p></div>@empty<p>No electoral rolls imported yet.</p>@endforelse
<h2>Import history</h2>@forelse($batches as $batch)<div class="row"><strong>{{ $batch->status }} · {{ $batch->state_name }} {{ $batch->year }} · AC {{ $batch->ac_code }} / Part {{ $batch->part }}</strong><p>{{ $batch->records_count }} entries · {{ $batch->created_at }}</p><small>{{ $batch->message }}</small></div>@empty<p>No admin uploads yet. Existing CLI imports appear in coverage above.</p>@endforelse
{{ $batches->links() }}
@endsection
