@extends('seo-layout')
@section('content')
<h1>Site management</h1><p>Manage the civic platform’s appearance, public APIs and application schedules.</p>
@if(!$ready)<p class="notice">Site management requires the pending database migration. Settings cannot be saved yet.</p>@endif
<nav class="admin-section-links"><a href="#appearance">Appearance</a> · <a href="#seo">Page SEO</a> · <a href="#operations">APIs & schedules</a> · <a href="#health">Monitoring</a></nav>
<section class="card" id="appearance"><h2>Brand, header, footer and theme</h2><form method="post" action="{{ route('site.appearance') }}">@csrf
@foreach(['name'=>'Site name','tagline'=>'Tagline','logo'=>'Logo image path (optional)','favicon'=>'Favicon image path (optional)','footer_text'=>'Footer description'] as $key=>$label)<div class="field"><label>{{ $label }}<input name="{{ $key }}" value="{{ $appearance[$key] }}" @if(in_array($key,['name','tagline','footer_text'])) required @endif></label></div>@endforeach
<p>Default: site name only. Upload PNG, JPG, WebP or ICO assets below, or use an existing local public image path. Clear the path to return to the name-only default.</p>
<div class="grid">@foreach(['primary','background','surface','text','muted','border','accent','header_background','header_text'] as $key)<label>{{ ucfirst(str_replace('_',' ',$key)) }}<input type="color" name="{{ $key }}" value="{{ $appearance[$key] }}"></label>@endforeach</div>
<label>Header template<select name="header_template">@foreach(['standard','compact'] as $value)<option @selected($appearance['header_template']===$value)>{{ $value }}</option>@endforeach</select></label>
<h3>Election map party colours</h3><div class="filters">@foreach($appearance['party_colors'] as $party=>$color)<label>{{ $party }}<input type="color" name="party_colors[{{ $party }}]" value="{{ $color }}"></label>@endforeach</div>
<label>Footer template<select name="footer_template">@foreach(['columns','compact'] as $value)<option @selected($appearance['footer_template']===$value)>{{ $value }}</option>@endforeach</select></label>
<h3>Footer contact and social profiles</h3><p>Leave a profile empty to hide it. <a href="{{ route('static-pages.index') }}">Manage footer pages and policies</a>.</p>
<label>Public contact email<input type="email" name="contact_email" value="{{ old('contact_email',$appearance['contact_email']) }}"></label>
<div class="grid">@foreach(config('site.appearance.socials') as $network=>$default)<label>{{ $network }} profile URL<input type="url" name="socials[{{ $network }}]" value="{{ old('socials.'.$network,$appearance['socials'][$network]??'') }}" placeholder="https://"></label>@endforeach</div>
<h3>Navigation links in header and footer</h3><p>Local paths only. The report link remains available in the footer. Admin sign-in is accessed directly by URL.</p>
<div data-navigation-editor>@foreach($appearance['links'] as $i=>$link)<div class="grid" data-link-row><label>Label<input name="links[{{ $i }}][label]" value="{{ $link['label'] }}" required maxlength="50"></label><label>Path<input name="links[{{ $i }}][url]" value="{{ $link['url'] }}" required maxlength="500"></label><button type="button" data-remove-link>Remove link</button></div>@endforeach</div><button type="button" data-add-link>Add navigation link</button>
<details><summary>Advanced palette: existing page and map colours</summary><p>Each existing colour is centralized here. These controls preserve legacy styles while allowing per-colour changes.</p><div class="grid">@foreach(config('site.palette') as $key=>$value)<label>{{ $key }}<input name="palette[{{ $key }}]" value="{{ $appearance['palette'][$key]??$value }}" pattern="#(?:[a-fA-F0-9]{3}|[a-fA-F0-9]{4}|[a-fA-F0-9]{6}|[a-fA-F0-9]{8})"></label>@endforeach</div></details><label>Additional CSS<textarea rows="7" name="css">{{ $appearance['css'] }}</textarea></label><p>Local CSS rules only. Use the theme variables; external resources and markup are blocked.</p><button @disabled(!$ready)>Save appearance</button></form>
<form action="{{ route('site.asset') }}" method="post" enctype="multipart/form-data">@csrf<h3>Upload brand image</h3><label>Use as<select name="kind"><option value="logo">Logo</option><option value="favicon">Favicon</option></select></label><input type="file" name="image" accept="image/png,image/jpeg,image/webp,image/x-icon" required><button @disabled(!$ready)>Upload and select image</button></form></section>
<section class="card" id="seo"><h2>SEO for any public page</h2><p><a href="{{ route('seo.index') }}">Bulk SEO drafts and revision restore</a></p>
@php $seoPath=request('path','/'); $meta=app(\App\Services\SeoPages::class)->current($seoPath); @endphp
<form method="get"><label>Load page path<input name="path" value="{{ $seoPath }}"></label><button>Load current metadata</button></form>
<form method="post" action="{{ route('site.seo') }}">@csrf<input type="hidden" name="path" value="{{ $seoPath }}"><input type="hidden" name="revision" value="{{ $meta?->revision_id??0 }}"><p>Editing {{ $seoPath }}</p><label>Title<input name="title" maxlength="160" value="{{ $meta?->title }}" required></label><label>Description<textarea name="description" maxlength="320" required>{{ $meta?->description }}</textarea></label><button>Save page SEO</button></form></section>
<section class="card" id="operations"><h2>Public API controls</h2><p>Read-only public data endpoints. Limits are requests per minute per client IP. Disabling an endpoint returns HTTP 503.</p>
@foreach($apis as $path=>$api)@php $control=$apiSettings[$path]??['enabled'=>true,'limit'=>120]; @endphp<form method="post" action="{{ route('site.api') }}">@csrf<input type="hidden" name="path" value="{{ $path }}"><h3>/{{ $path }}</h3><p>{{ $api['methods'] }} · {{ $api['handler'] }}</p><label>Status<select name="enabled"><option value="1" @selected($control['enabled'])>Enabled</option><option value="0" @selected(!$control['enabled'])>Disabled</option></select></label><label>Requests per minute<input type="number" name="limit" min="1" max="10000" value="{{ $control['limit'] }}"></label><button @disabled(!$ready)>Save API control</button></form>@endforeach
<h2>External integrations</h2><p><a href="{{ route('ai.settings') }}">AI providers and encrypted API keys</a> · <a href="{{ route('pdf-storage.index') }}">Document storage</a> · <a href="{{ route('imports.index') }}">Official source connectors</a></p>
@foreach($connectors as $connector)<details><summary>{{ $connector->name }} · {{ $connector->format }}</summary><p>Fetches the official source into reviewable import evidence. Changes affect future checks; previous receipts keep their original URL.</p><form method="post" action="{{ route('site.connector',$connector->id) }}">@csrf<label>Name<input name="name" value="{{ $connector->name }}" required></label><label>Official source URL<input name="url" type="url" value="{{ $connector->url }}" required></label><label>Automatic checks<select name="automatic"><option value="0" @selected(!$connector->automatic)>Paused</option><option value="1" @selected($connector->automatic)>Enabled</option></select></label><button>Save connector</button></form></details>@endforeach
<h2>Application schedules</h2><p>The server must run Laravel’s scheduler every minute. These controls change future runs, not active processes. Times use Asia/Kolkata.</p>
<h3>Official election releases</h3><p>Supported new Assembly workbook editions are imported with original files, source hashes and extraction notes. Lok Sabha, by-election and changed layouts stay listed for review.</p><form method="post" action="{{ route('site.elections.sync') }}">@csrf<button @disabled(!$ready)>Check and import now</button></form>
@php $electionSync=app(\App\Services\ElectionReleaseImporter::class)->latest(); @endphp
@if($electionSync)<p>Last check: {{ $electionSync['checked_at'] }} · Imported: {{ count($electionSync['imported']) }} · Needs review: {{ count($electionSync['needs_review']) }}</p>
@foreach($electionSync['needs_review'] as $edition)<p>{{ strtoupper($edition['kind']) }} {{ $edition['year'] }} · <a href="{{ $edition['url'] }}">Official source</a> · {{ $edition['reason'] }}</p>@endforeach
@endif
@foreach($tasks as $key=>$task)<form method="post" action="{{ route('site.task',$key) }}">@csrf<h3>{{ ucfirst(str_replace('_',' ',$key)) }}</h3><p>{{ $task['purpose'] }}</p><code>{{ $task['command'] }}</code><label>Status<select name="enabled"><option value="1" @selected($task['enabled'])>Enabled</option><option value="0" @selected(!$task['enabled'])>Paused</option></select></label><label>Schedule<select name="schedule">@foreach(\App\Services\ManagedTasks::FREQUENCIES as $value=>$label)<option value="{{ $value }}" @selected($task['schedule']===$value)>{{ $label }}</option>@endforeach</select></label><button @disabled(!$ready)>Save schedule</button></form>@endforeach
<h3>Server-managed Census workers</h3><p>Primary catalogue/text worker and OCR batch worker: extraction is paused by project instruction. Their independent server crons, resource ledger and SQLite queues are outside this application. This page does not resume or modify them; current runtime status must be checked on the worker host.</p></section>
<section class="card" id="health"><h2>Monitoring</h2><p>Refreshes every 60 seconds while this section is open. A missing or old heartbeat is not a healthy result. Expected monitor interval: {{ \App\Services\ManagedTasks::FREQUENCIES[$tasks['monitor']['schedule']] }}.</p><table><thead><tr><th>Task</th><th>Last result</th><th>Last seen (server time)</th><th>Details</th></tr></thead><tbody>@forelse($health as $row)<tr><td>{{ $row->key }}</td>@php $schedule=$tasks[$row->key==='health'?'monitor':$row->key]['schedule']??'*/5 * * * *'; $minutes=match($schedule){'* * * * *'=>3,'*/5 * * * *'=>12,'*/15 * * * *'=>35,'0 * * * *'=>125,'30 6 * * 0'=>11520,default=>1500}; $stale=\Carbon\Carbon::parse($row->checked_at)->lt(now()->subMinutes($minutes)); @endphp<td>{{ $stale?'Stale heartbeat — check scheduler':$row->status }}</td><td>{{ $row->checked_at }} ({{ \Carbon\Carbon::parse($row->checked_at)->diffForHumans() }})</td><td>{{ $row->details }}</td></tr>@empty<tr><td colspan="4">No heartbeat recorded yet. Verify the scheduler and monitor command.</td></tr>@endforelse</tbody></table></section>
<section class="card"><h2>Recent administrative changes</h2>@foreach($changes as $change)<p>{{ $change->created_at }} · {{ $change->target }} · {{ $change->reason }} · administrator {{ $change->user_id }}</p>@endforeach</section>
<script>setInterval(()=>{if(location.hash==='#health'&&!document.hidden&&!document.querySelector('form[data-dirty]'))location.reload()},60000);document.querySelectorAll('form').forEach(f=>f.addEventListener('input',()=>f.dataset.dirty='true'));</script>
@endsection
