<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
@include('seo-metadata', ['breadcrumbs'=>['India'=>route('home'),$title=>route('states.show',['state'=>$state])], 'canonical'=>route('states.show',['state'=>$state]), 'seoTitle'=>$title.' Census, elections & civic records · Pollmedia', 'seoDescription'=>'Explore available turnout, party vote shares and winning margins with constituency results and official sources.'])
<link rel="stylesheet" href="/css/election-dashboard.css?v={{ substr(hash_file('sha256', public_path('css/election-dashboard.css')), 0, 12) }}"><script src="/js/instant-filters.js?v={{ substr(hash_file('sha256',public_path('js/instant-filters.js')),0,12) }}" defer></script>@include('site-theme')<link rel="stylesheet" href="{{ asset('css/civic-pages.css') }}?v={{ substr(hash_file('sha256',public_path('css/civic-pages.css')),0,12) }}"><script src="/js/history-lines.js?v={{ substr(hash_file('sha256',public_path('js/history-lines.js')),0,12) }}" defer></script><script src="/js/state-fragments.js?v={{ substr(hash_file('sha256',public_path('js/state-fragments.js')),0,12) }}" defer></script></head><body class="election-ui civic-design state-design public-place-page">
@include('public-header')
<div class="dashboard-shell">
<main class="dashboard-main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('home') }}">{{ \App\Services\PublicLanguage::text('India') }}</a><span>/</span><span aria-current="page">{{ $title }}</span></nav>
<section class="place-intro"><div><p class="section-label">{{ $stateSummary['kind'] }} · {{ \App\Services\PublicLanguage::text('State overview') }}</p><h1>{{ $title }}</h1><div class="intro-links"><a href="#politics">{{ \App\Services\PublicLanguage::text('Find a district or constituency') }} ↓</a><a href="#state-evidence">{{ \App\Services\PublicLanguage::text('Sources') }} ↓</a></div></div></section>
<nav class="state-jump-links" aria-label="State topics"><a href="#pc-history">Lok Sabha</a><a href="#ac-history">State Assembly</a><a href="#politics">Districts & constituencies</a><a href="{{ route('elections.by-election-results') }}">By-elections ↗</a><a href="{{ route('civic.index',['state'=>$state]) }}">Census & places ↗</a></nav>
<div id="election-analysis">
@foreach(['pc'=>'Lok Sabha','ac'=>'State Assembly'] as $sectionKind=>$sectionLabel)
@include('state-election-section',['kind'=>$sectionKind,'sectionLabel'=>$sectionLabel,'history'=>$electionSections[$sectionKind]['history'],'edition'=>$electionSections[$sectionKind]['edition'],'election'=>$electionSections[$sectionKind]['election']])
@endforeach
</div>
<section class="panel" id="politics"><h2>Districts and constituencies</h2><p><a href="#pc-constituencies">Lok Sabha constituencies →</a> · <a href="#ac-constituencies">Assembly constituencies →</a></p><form data-manual-submit data-fragment-form data-target="politics" class="filters" method="get"><input type="hidden" name="election" value="{{ $kind }}"><div><label for="place">Choose an available place</label><select name="place" id="place"><option value="">All linked profiles</option>@foreach($options as $option)<option value="{{ $option->slug }}" @selected($selected===$option->slug)>{{ $option->name }} {{ strtoupper($option->type) }}</option>@endforeach</select></div><div><label for="type">Page type</label><select name="type" id="type"><option value="">{{ \App\Services\PublicLanguage::text('All types') }}</option>@foreach(['pc'=>'PC','ac'=>'AC','district'=>'District'] as $key=>$label)<option value="{{ $key }}" @selected($type===$key)>{{ $label }}</option>@endforeach</select></div><button>Find profile</button></form><p class="small">{{ $places->total() }} {{ \Illuminate\Support\Str::plural('place', $places->total()) }}</p><div class="place-list">@foreach($places as $place)<a href="{{ route('places.show',['type'=>$place->type,'slug'=>substr($place->slug,strlen($place->type)+1)]) }}">{{ $place->name }} {{ strtoupper($place->type) }} →</a>@endforeach</div>{{ $places->links() }}</section>
<section class="panel" id="state-evidence"><h2>{{ $title }} election coverage</h2><h3>Assembly archive</h3><a href="{{ route('elections.assembly-sources',['state'=>$title]) }}">Browse {{ $title }} Assembly sources</a><p><a href="{{ route('elections.assembly') }}">Assembly results</a> · <a href="{{ route('elections.history') }}">Lok Sabha results</a></p></section>
@include('election-methodology',['isStateHistory'=>true])
</main><aside class="dashboard-sidebar" aria-label="State map and related pages">@include('place-location-map',['mapName'=>$title,'mapQuery'=>$title.', India'])<section class="panel"><h2>Explore {{ $title }}</h2><nav class="sidebar-links" aria-label="Related pages"><a href="#pc-history">Lok Sabha →</a><a href="#ac-history">State Assembly →</a><a href="#politics">Districts & constituencies ↓</a><a href="#state-evidence">Official sources ↓</a><a href="{{ route('elections.by-election-results') }}">By-elections →</a><a href="{{ route('civic.index',['state'=>$state]) }}">Census & places →</a></nav></section></aside></div><script src="/js/sortable-tables.js?v={{ substr(hash_file('sha256', public_path('js/sortable-tables.js')), 0, 12) }}" defer></script>@include('public-footer')</body></html>
