<section id="{{ $kind }}-history" class="state-election-section" aria-label="{{ $sectionLabel }} history and results">
<div class="state-section-heading"><div><p class="section-label">{{ $title }} · {{ strtoupper($kind) }}</p><h2>{{ $sectionLabel }}</h2><p>Historical voting trends and results by election year</p></div><a href="#{{ $kind }}-results">Jump to year results ↓</a></div>
@if($history)
<p class="coverage-note">Coverage varies by year. Turnout combines votes and electors from constituencies with available figures; the winning margin is their average. Some years have partial coverage.</p>
@include('place-history-charts',['stateHistory'=>$history,'chartTableAnchor'=>$kind.'-coverage'])
<details class="panel" id="{{ $kind }}-coverage"><summary>Historical coverage and original editions</summary><div class="table-scroll"><table data-sortable><thead><tr><th>Report / year</th><th>Turnout</th><th>Turnout coverage</th><th>Margin coverage</th><th>Party coverage</th><th>Candidate rows</th></tr></thead><tbody>@foreach($history as $row)<tr><th><a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$row['id'],'state'=>$row['state']]) }}">{{ $row['label'] }}</a></th><td>{{ $row['turnout']===null?'—':number_format($row['turnout'],2).'%' }}@if($row['turnout_review_count']??0) †@endif</td><td>{{ $row['turnout_count'] }} / {{ $row['tables'] }}</td><td>{{ $row['margin_count'] }} / {{ $row['tables'] }}</td><td>{{ $row['party_count'] }} / {{ $row['tables'] }}</td><td>{{ number_format($row['candidate_rows']??0) }} candidate rows · <a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$row['id'],'state'=>$row['state']]) }}">View candidate tables →</a></td></tr>@endforeach</tbody></table></div></details>
@endif
<section id="{{ $kind }}-results" class="panel state-year-results"><p class="section-label">{{ $sectionLabel }} · individual election</p><h2>Results by year</h2>
<form class="state-year-form" method="get" action="{{ route('states.show',['state'=>$state]) }}#{{ $kind }}-results"><input type="hidden" name="{{ $kind==='pc'?'ac_edition':'pc_edition' }}" value="{{ $electionSections[$kind==='pc'?'ac':'pc']['edition'] }}"><label for="{{ $kind }}-edition">{{ $sectionLabel }} election year</label><div><select id="{{ $kind }}-edition" name="{{ $kind }}_edition" @disabled(!$history)>@forelse(collect($history)->groupBy('year')->map(fn($group)=>$group->firstWhere('id',$edition)??$group->first()) as $row)<option value="{{ $row['id'] }}" @selected($edition===$row['id'])>{{ $row['year'] }}</option>@empty<option>No available election years</option>@endforelse</select><button @disabled(!$history)>Show results</button></div></form>
@if($election)
<h3>{{ $election['year'] }} {{ $sectionLabel }} results</h3><div class="state-year-metrics"><div><span>Votes polled</span><strong>{{ $election['polled']===null?'—':number_format($election['polled']) }}@if($election['turnout_review_count']??0) †@endif</strong></div><div><span>Turnout</span><strong>{{ $election['turnout']===null?'—':number_format($election['turnout'],2).'%' }}@if($election['turnout_review_count']??0) †@endif</strong></div><div><span>Mean winning margin</span><strong>{{ $election['margin']===null?'—':number_format($election['margin']) }}@if($election['margin_review_count']??0) †@endif</strong></div><div><span>Available constituencies</span><strong>{{ number_format($election['tables']) }}</strong></div></div>
<p class="small">{{ $election['label'] }} · turnout covers {{ $election['turnout_count'] }} of {{ $election['tables'] }} constituencies; mean margin covers {{ $election['margin_count'] }}. † marks figures with source notes.</p>
@if(($election['review_count']??0)||($election['party_review_count']??0)||($election['turnout_review_count']??0))<p class="coverage-note">This election includes records with data notes. <a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$edition,'state'=>$election['state']]) }}">View results and notes →</a></p>@endif
<h3>Party vote shares · {{ $election['year'] }}</h3><div class="table-scroll"><table data-sortable><thead><tr><th>Party at election</th><th>Votes</th><th>Share</th></tr></thead><tbody>@forelse($election['parties'] as $item)<tr><th>{{ $item['party'] }}</th><td>{{ number_format($item['votes']) }}</td><td>{{ number_format($item['share'],2) }}%@if($election['party_review_count']??0) †@endif</td></tr>@empty<tr><td colspan="3">No comparable party totals are available for this year.</td></tr>@endforelse</tbody></table></div>
<details class="state-winners"><summary>Constituency winners and margins · {{ $election['year'] }}</summary><p class="small">Winners and vote margins from the available constituency results.</p><div class="table-scroll"><table data-sortable><thead><tr><th>Constituency</th><th>Winner</th><th>Party</th><th>Margin (votes)</th></tr></thead><tbody>@forelse($election['winners']??[] as $winner)<tr><th><a href="{{ route('constituency.overview',['kind'=>$kind,'state'=>$title,'name'=>$winner['constituency'],'edition'=>$edition]) }}">{{ $winner['constituency'] }}</a></th><td>{{ $winner['candidate'] }}</td><td>{{ $winner['party'] }}</td><td>{{ number_format($winner['margin']) }}</td></tr>@empty<tr><td colspan="4">Winner details are not available for this year.</td></tr>@endforelse</tbody></table></div></details>
<p class="state-result-links"><a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$edition,'state'=>$election['state']]) }}">All constituency results for {{ $election['year'] }} →</a><a href="{{ $election['source_url'] }}" target="_blank" rel="noopener">Official report ↗</a></p>
@else<p>No {{ $sectionLabel }} results are available for {{ $title }} in this collection yet.</p>@endif
</section>
@include('state-constituency-directory')
</section>
