<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>{{ $title }} · {{ $kind==='pc'?'Lok Sabha':'Assembly' }} history report</title>
@include('site-theme')
<link rel="stylesheet" href="/css/history-report.css?v={{ substr(hash_file('sha256',public_path('css/history-report.css')),0,12) }}"></head><body class="history-report">
<div class="report-actions"><button onclick="window.print()">Print / Save as PDF</button><p>All chart values and official references are included.</p></div>
<header class="report-masthead"><div class="report-brand">{{ app(\App\Services\SiteSettings::class)->appearance()['name'] }}<span>State election history</span></div><h1>{{ $title }}</h1><p class="report-subtitle">{{ $kind==='pc'?'Lok Sabha':'State Assembly · AC' }}</p><div class="report-meta"><span>{{ collect($history)->min('year') }}–{{ collect($history)->max('year') }} · reference years</span><span>Prepared {{ now()->format('d M Y') }}</span></div></header>
<main>
@include('printable-election-map',['printMapState'=>$title])
@include('place-history-charts',['reportMode'=>true,'stateHistory'=>$history])
<section><h2>Sources and coverage by election year</h2><table><thead><tr><th>Year</th><th>Available constituencies</th><th>Turnout coverage</th><th>Margin coverage</th><th>Party coverage</th></tr></thead><tbody>@foreach($history as $row)<tr><th>{{ $row['year'] }}</th><td>{{ $row['tables'] }}</td><td>{{ $row['turnout_count'] }}</td><td>{{ $row['margin_count'] }}</td><td>{{ $row['party_count'] }}</td></tr>@endforeach</tbody></table>
@foreach($history as $row)<article class="source-note"><h3>{{ $row['label'] }}</h3><a href="{{ $row['source_url'] }}">{{ $row['source_url'] }}</a><p><a href="{{ route($kind==='pc'?'elections.history':'elections.assembly',['edition'=>$row['id'],'state'=>$row['state']]) }}">Constituency results and source notes · {{ $row['year'] }}</a></p>@if(($row['turnout_review_count']??0)||($row['margin_review_count']??0)||($row['party_review_count']??0))<p>† This year contains figures with source notes. These notes accompany the linked constituency results.</p>@endif</article>@endforeach</section>
@include('election-methodology',['isStateHistory'=>true])
</main><footer><strong>Pollmedia</strong><a href="{{ route('states.show',['state'=>$state]) }}#{{ $kind }}-history">Interactive state history and updated sources</a></footer></body></html>
