@extends('village-layout')
@section('title', 'Pilibhit village directory · Census editions')
@section('description', 'Browse official Census data by district, subdistrict and village, with historical source editions.')
@section('content')
<div class="kicker">Official Census geography</div><h1>Choose your area.</h1><p class="lead">Choose a Census edition, then narrow the villages by historical geography or the dated current LGD directory.</p>
<form method="get" action="{{ route('villages.index') }}" class="search" id="village-filters">
<div><label for="census-year">Census edition</label><select id="census-year" name="year"><option value="2011" @selected($year==='2011')>2011 — village data</option><option value="2001" @selected($year==='2001')>2001 — village data</option></select></div>
<div><label for="census-state">State</label><select id="census-state"><option>Uttar Pradesh</option></select></div>
<div><label for="census-district">District</label><select id="census-district" name="district"><option value="{{ $year==='2001' ? '21' : '151' }}">Pilibhit</option></select></div>
<div><label for="census-subdistrict">Census subdistrict / tehsil</label><select id="census-subdistrict" name="subdistrict"><option value="">Choose a subdistrict</option>@foreach($census['subdistricts'] as $area)<option value="{{ $area['code'] }}" @selected($subdistrict===$area['code'])>{{ $area['name'] }} · {{ $area['code'] }}</option>@endforeach</select></div>
<div><label for="census-block">Historical block (2011)</label><select id="census-block" name="block" @disabled($year!=='2011')><option value="">{{ $year==='2011' ? 'All verified 2011 blocks' : '2001 block mapping not verified' }}</option>@foreach($blocks as $name)<option value="{{ $name }}" @selected($block===$name)>{{ $name }}</option>@endforeach</select></div>
<div><label for="electoral-pc">Parliamentary constituency (LGD)</label><select id="electoral-pc" name="pc"><option value="">All / not selected</option><option value="pilibhit" @selected($pc==='pilibhit')>Pilibhit PC</option></select></div>
<div><label for="electoral-ac">Assembly constituency (LGD)</label><select id="electoral-ac" name="ac"><option value="">All available ACs</option>@foreach($assemblyOptions as $slug)<option value="{{ $slug }}" @selected($ac===$slug)>{{ ucfirst($slug) }} AC</option>@endforeach</select></div>
<div><label for="current-subdistrict">Current LGD subdistrict / tehsil</label><select id="current-subdistrict" name="current_subdistrict"><option value="">All available current tehsils</option>@foreach($currentSubdistricts as $area)<option value="{{ $area['code'] }}" @selected($currentSubdistrict===$area['code'])>{{ $area['name'] }} · {{ $area['code'] }}</option>@endforeach</select></div>
<div><label for="current-block">Current LGD block</label><select id="current-block" name="current_block"><option value="">All available current blocks</option>@foreach($currentBlocks as $area)<option value="{{ $area['code'] }}" @selected($currentBlock===$area['code'])>{{ $area['name'] }} · {{ $area['code'] }}</option>@endforeach</select></div>
<div><label for="current-panchayat">Current gram panchayat</label><select id="current-panchayat" name="panchayat"><option value="">All available gram panchayats</option>@foreach($panchayats as $area)<option value="{{ $area['code'] }}" @selected($panchayat===$area['code'])>{{ $area['name'] }} · {{ $area['code'] }}</option>@endforeach</select></div>
<div><label for="census-village">Village</label><select id="census-village" name="village" @disabled(!$hasSelection)><option value="">{{ !$hasSelection ? 'Choose an area first' : 'All villages in this selection' }}</option>@foreach($options as $v)<option value="{{ $v['code'] }}" @selected($selectedVillage===$v['code'])>{{ $v['name'] }} · {{ $v['code'] }}</option>@endforeach</select></div>
<button type="submit">Show selection</button><a href="{{ route('villages.index') }}">Reset</a></form>
@if($year==='2001')<p class="notice">The 2001 workbook includes 1,216 inhabited villages. The handbook also records 133 uninhabited villages; those are not included in these population-table profiles. <a href="https://censusindia.gov.in/nada/index.php/catalog/43939/download/47621/DH_09_2001_PIL.pdf">Open 2001 handbook PDF ↗</a></p>@endif
<p class="small">2011 block assignments: 1,428 of 1,435 village records verified; seven forest records remain unmapped. <a href="{{ $mapping['url'] }}">Official block and location-code tables ↗</a></p><p class="notice">All {{ number_format(count($census['villages'])) }} village records from the Pilibhit {{ $year }} workbook are available. Current administration uses the LGD snapshot downloaded {{ $lgd['checked_on'] }}. These filters locate historical Census profiles; they do not turn historical population counts into current figures. Electoral filters use the official LGD PC/AC report checked {{ $electoral['checked_on'] }}. Profiles without a matching village code are excluded only when an electoral filter is selected. <a href="{{ $lgd['url'] }}">Official LGD directory ↗</a></p>
@if(!$hasSelection)
<div class="card">Choose a constituency, subdistrict, block or gram panchayat to see matching villages.</div>
@else
<p class="small" role="status">{{ number_format($villages->total()) }} village profiles in this selection. Showing {{ $villages->firstItem() ?? 0 }}–{{ $villages->lastItem() ?? 0 }}.</p><div class="grid">@foreach($villages as $v)<article class="card"><span class="tag">Census village · {{ $v['code'] }}</span><h3><a href="{{ route('villages.show',['code'=>$v['code'],'slug'=>\Illuminate\Support\Str::slug($v['name']),'year'=>$year]) }}">{{ $v['name'] }} →</a></h3><p>{{ number_format($v['population']) }} people · {{ number_format($v['households']) }} households</p><p class="small">Pilibhit district · Census {{ $year }}</p></article>@endforeach</div><nav class="links" aria-label="Village result pages">@if($villages->previousPageUrl())<a href="{{ $villages->previousPageUrl() }}">← Previous</a>@endif @if($villages->hasMorePages())<a href="{{ $villages->nextPageUrl() }}">Next →</a>@endif</nav>
@endif
<script>
const form=document.getElementById('village-filters');
const dependents={year:['district','subdistrict','block','pc','ac','current_subdistrict','current_block','panchayat','village'],subdistrict:['block','pc','ac','current_subdistrict','current_block','panchayat','village'],block:['pc','ac','current_subdistrict','current_block','panchayat','village'],pc:['ac','current_subdistrict','current_block','panchayat','village'],ac:['current_subdistrict','current_block','panchayat','village'],current_subdistrict:['current_block','panchayat','village'],current_block:['panchayat','village'],panchayat:['village'],village:[]};
for(const [name,clear] of Object.entries(dependents)){form.elements.namedItem(name).addEventListener('change',()=>{for(const child of clear){form.elements.namedItem(child).value=''}form.submit()})}
</script>
@endsection
